requires 'Archive::Any::Lite';
requires 'Archive::Zip', '!= 1.66, != 1.67, != 1.68';
requires 'Badge::Simple';
requires 'CPAN::Audit';
requires 'CPAN::Common::Index';
requires 'Cache::FileCache';
requires 'Class::Method::Modifiers';
requires 'Const::Fast';
requires 'DBD::SQLite';
requires 'DBI';
requires 'DBIx::TransactionManager';
requires 'Data::Binary';
requires 'Data::Dump';
requires 'Digest::FNV::XS';
requires 'Digest::MD5';
requires 'Email::Sender', '1.300028';
requires 'Encode';
requires 'Exporter', '5.57';
requires 'File::Copy::Recursive';
requires 'File::Path::Tiny', '1.0';
requires 'File::Temp';
requires 'File::Which';
requires 'Gravatar::URL';
requires 'HTML::Entities';
requires 'HTTP::Status';
requires 'HTTP::Tiny::Mech';
requires 'Hash::Merge::Simple';
requires 'IO::Socket::SSL';
requires 'Imager';
requires 'Imager::Filter::RoundedCorner';
requires 'JSON::Validator';
requires 'JSON::XS', '4.0';
requires 'LWP::Protocol::https';
requires 'LWP::UserAgent';
requires 'List::Util', '1.45';
requires 'Log::Handler';
requires 'Log::Handler::Output::File::Stamper';
requires 'Menlo::CLI::Compat';
requires 'MetaCPAN::Client';
requires 'Mock::MonkeyPatch';
requires 'Module::CoreList';
requires 'Module::Find';
requires 'Module::Runtime';
requires 'Module::Version';
requires 'Mojo::JSON::Pointer';
requires 'Mojolicious', '8.00';
requires 'Mojolicious::Plugin::OpenAPI';
requires 'MooX::Singleton';
requires 'Parallel::Runner';
requires 'Parse::CPAN::Whois';
requires 'Parse::Distname';
requires 'Parse::PMFile';
requires 'Path::Tiny';
requires 'Plack';
requires 'Plack::Middleware::ReverseProxy';
requires 'Plack::Runner';
requires 'Regexp::Common';
requires 'Role::Tiny::With';
requires 'SQL::Maker';
requires 'String::CamelCase';
requires 'Syntax::Keyword::Try';
requires 'Test::Deep';
requires 'Test::MockTime::HiRes';
requires 'Test::TCP';
requires 'Text::Diff';
requires 'Time::Duration';
requires 'Time::HiRes';
requires 'Time::Moment';
requires 'Time::Zone';
requires 'URI';
requires 'WWW::Mechanize::Cached';
requires 'WorePAN', '0.16';
requires 'XML::Atom::SimpleFeed';
requires 'XML::LibXML::SAX';
requires 'perl', '5.028';
requires 'version';
recommends 'Module::CPANfile';

on test => sub {
    requires 'Mojo::Base';
    requires 'Path::Tiny';
    requires 'Syntax::Keyword::Try';
    requires 'Test::Deep';
    requires 'Test::FailWarnings';
    requires 'Test::MockTime::HiRes';
    requires 'Test::More', '0.88';
    requires 'Test::Perl::Critic';
    requires 'Test::RequiresInternet';
};

on develop => sub {
    requires 'CPAN::Common::Index';
    requires 'CSS::LESS::Filter';
    requires 'DBI';
    requires 'Data::Dump';
    requires 'Devel::Cover';
    requires 'Devel::NYTProf';
    requires 'Email::Sender';
    requires 'Email::Simple';
    requires 'File::Copy::Recursive';
    requires 'File::pushd';
    requires 'Furl';
    requires 'Hash::Diff';
    requires 'JSON::XS';
    requires 'Menlo::CLI::Compat';
    requires 'Mojo::Base';
    requires 'Params::Validate';
    requires 'Path::Extended::Tiny';
    requires 'Path::Tiny';
    requires 'Perl::PrereqScanner::NotQuiteLite', '0.9911';
    requires 'Perl::PrereqScanner::NotQuiteLite::App';
    requires 'Perl::Tidy';
    requires 'Regexp::Trie';
    requires 'Role::Tiny::With';
    requires 'Software::License';
    requires 'String::CamelCase';
    requires 'Syntax::Keyword::Try';
    requires 'Test::CPANfile', '0.07';
    requires 'Test::Perl::Critic';
    requires 'Text::Diff';
    requires 'Text::Sass::XS';
    recommends 'DBD::mysql';
};
feature 'acme', 'acme' => sub {
    requires 'Acme::CPANAuthors';
};

feature 'extlib', 'extlib' => sub {
    requires 'Array::Diff';
    requires 'CPAN::DistnameInfo';
    requires 'CPAN::Meta::Converter';
    requires 'CPAN::Meta::YAML';
    requires 'Capture::Tiny';
    requires 'Class::Accessor::Fast';
    requires 'Config::INI::Reader';
    requires 'Data::Binary';
    requires 'Email::Sender';
    requires 'Email::Simple';
    requires 'File::Find::Object';
    requires 'File::chdir';
    requires 'Furl::HTTP';
    requires 'JSON::PP', '4.00';
    requires 'Module::CPANfile';
    requires 'Module::Signature';
    requires 'Params::Validate';
    requires 'Parse::LocalDistribution';
    requires 'Perl::PrereqScanner::NotQuiteLite', '0.9902';
    requires 'Pod::Simple';
    requires 'Software::License', '0.103012';
    requires 'Software::LicenseUtils';
    requires 'perl', '5.008001';
};

feature 'performance', 'performance' => sub {
    requires 'Algorithm::Diff::XS';
    requires 'Cookie::Baker::XS';
    requires 'HTTP::Parser::XS';
    requires 'Unicode::UTF8';
    requires 'WWW::Form::UrlEncoded::XS';
};

feature 'production', 'production' => sub {
    requires 'Config::Crontab';
    requires 'Fluent::Logger';
    requires 'Starman';
    requires 'Text::Diff::Unified::XS';
};
