use strict;
use warnings;
use Test::More;

plan skip_all => 'todo';

done_testing;

__DATA__
# implausibly old time stamp
ASANDSTRM/XML-Parser-2.26-bin-1-MacOS.tgz

# Cannot mknod: Operation not permitted
BPORTER/ngbbs/ngbbs-0.1.6.tar.bz2

# not look like a tar archive
CAPOEIRAB/WWW-Salesforce-0.03.tar.gz
CAPOEIRAB/WWW-Salesforce-0.04.tar.gz
CAPOEIRAB/WWW-Salesforce-Simple-0.07.tar.gz
CLCL/WebService-KuronekoYamato-v0.0.4.tar.gz
CLCL/WebService-NiigataUnyu-v0.0.1.tar.gz
CLCL/WebService-NiigataUnyu-v0.0.3.tar.gz
CLCL/WebService-SagawaKyubin-0.0.1.tar.gz
CLCL/WebService-SagawaKyubin-v0.0.2.tar.gz
CLCL/WebService-SagawaKyubin-v0.0.3.tar.gz
DAZJORZ/Term-Prompt-0.05.tar.gz
DAZJORZ/term-prompt-0.05.tar.gz
DCANTRELL/Tie-Hash-Longest-1.0.reupload.tar.gz
DCANTRELL/Tie-Hash-Longest-1.0.tar.gz
DRBEAN/Games-Tournament-Swiss-004/tables-0.04.tar.gz
FREMAN/Device-Inverter-Aurora.0.01.tar.gz
GENE/Chess-Coverage-0.0101.tar.gz
GENE/Chess-Coverage-0.03.tar.gz
ILYAZ/modules/Math-Pari-2.0305_01080604.tar.gz
JJONES/SMS-Send-UK-Kapow-0.03.tar.gz
KHW/Unicode-Casing-09.tar.gz
KORSANI/Log-Funlog-0.88.tar.gz
KORSANI/Log-Funlog-0.89.tar.gz
LBENDAVID/DBD-TSM-0.12.tar.gz
LBENDAVID/DBD-TSM/DBD-TSM-0.11.tar.gz
MANOWAR/RadiusPerl-0.07.tar.gz
NYAKNYAN/HTTP-Server-EV-0.21.tar.gz
PETERGAL/PGForth1.1.tar.gz
PYTHIAN/DBD-Oracle-1.24.tar.gz
SMUELLER/PAR-0.953.tar.gz
TLINDEN/WWW-Dict-Leo-Org-1.32.tar.gz

# unexpected end of file
CHRMUE/Socket-Class-2.14.tar.gz
CLKAO/SVK-v2.0.0_91.tar.gz
CNANDOR/Compress-Zlib-1.01-bin-1-MacOS.tar.gz
DAGOLDEN/Module-Build-0.34_03.tar.gz
JESSE/RT-OnlineDocs-0.04.tar.gz
MARTINB/Xforms4Perl-0.8.4-2.tgz
MSCHILLI/Sysadm-Install-0.26.tar.gz
SATOH/List-Enumerator-0.06.tar.gz

# compress: Cannot exec: No such file or directory
DAUNAY/oEdtk.20070321.v0.31.tar.gz
ILYAZ/etext/etext0.6.0.tar.gz
ILYAZ/etext0.6.0.tar.gz
MARCLANG/ParallelUserAgent-2.37.tar.gz
OWEN/Math-RPN-1.03.tar.gz
OWEN/Math-RPN-1.05.tar.gz
SCHOEN/R3-0.01.tar.gz
SCHOEN/R3-conn-0.20.tar.gz
SCHOEN/R3-func-0.20.tar.gz
SCHOEN/R3-itab-0.20.tar.gz
SCHOEN/R3-rfcapi-0.20.tar.gz
SCHOEN/R3-rfcapi-0.21.tar.gz

# Cannot open: File exists
HOOO/X3D-0.00.1.tar.gz
YEWEI/test.tgz

# gzip: stdin: decompression OK, trailing garbage ignored
JACKS/Usage-beta.tar.gz

# gzip: stdin: invalid compressed data--format violated
JCAMACHO/Catalyst-Controller-FormBuilder-0.01_01.tar.gz

# tar: Skipping to next header
JHARDING/aol-toc-0.3.tar.gz

# Cannot open: No such file or directory
LEMBARK/Schedule-Depend-0.08.tar.gz
LEMBARK/Schedule-Depend-0.27.tar.gz

# tar: Unexpected EOF in archive
XYF/C3000-0.0052.tar.gz

# ZIP
AFRYER/TUXEDO-1_00.zip
AMGARLAND/DirFiles_1_0.zip
ASTILLER/DBD_RDB-1_13.ZIP
ASTILLER/DBD_RDB-1_14.ZIP
ASTILLER/DBD_RDB-1_15.ZIP
ATIFK/nmrwdog-0.1.zip
BYOURTH/Math.SimpleInterest.0.02.ZIP
BYOURTH/Math.SimpleInterest.0.03.ZIP
BYOURTH/Math.SimpleInterest.0.04.ZIP
DAVEROTH/Win32-API-Prototype/Win32-API-Prototype_AllBuilds.Zip
DSUGAL/VMS-MISC-1_00.ZIP
FERNANDES/155.zip
FERNANDES/Reduziguais.zip
FGLOCK/Myfile-0.01.zip
GSLONDON/iperl.20040205.zip
ILYAZ/os2/perl5.00301.os2.zip
JBAKER/Apache-Session-0.10.zip
JBAKER/mod_perl-1.07_04-bin-bindist1-i386-win32-vc5.zip
JOCASA/futils.02Jun96.zip
KULCHENKO/SOAP-Lite-0.55.zip
MAKAROW/DBIx-Web-0.60a.tar.zip
MAKAROW/DBIx-Web-0.62a.tar.zip
NREICHEN/eicndhcpd_11.zip
NREICHEN/eicndhcpd_v11_src.ZIP
PAUL/Foo-0.0.1-beta1.zip
PHOENIXL/extensible_report_generator_1.12.zip
PHOENIXL/extensible_report_generator_1.13.zip
PTILL/mod_perl-1.11_1-apache-1.3b7dev-bin-bindist1-i386-win95-vc5.zip
RICHARDC/testmy-cgi-v.1.zip
RICHARDC/testmycgi-v.1.zip
RICHARDC/testmycgi-v0.1.zip
RJE/BURL-0.5.zip
RJE/UWP-0.8.zip
RJSRI/QXP-Validate-1.0.zip
ROOTKWOK/Win32-SysPrivilege-v0.02.zip
RURBAN/perlhlp.zip
SCHUBIGER/scripts/newsletter-1.4.zip
SCHUBIGER/scripts/newsletter-1.5.zip
SCHUBIGER/scripts/newsletter-1.6.zip
SCHUBIGER/scripts/newsletter-1.7.zip
SCHWA/FFI-1.04-dll.zip
SNEEX/HTML_Month.v6a.zip
SNEEX/Post_FormMail.zip
VLADB/cvs_init_1_01.zip
WARTHURT/Memo32-1.00.zip



# Can be extracted at least with /bin/tar but Archive::Tar reveals serious issue

# mknod: Operation failed
ANGERSTEI/Net-Ping-Network-1.55.tar.gz

# Can't call method list_files
ANGERSTEI/Net-Ping-Network-1.57.tar.gz
BROWSERUK/Used/Used-0.01.tar.gz
CHIA/Regexp-Tr-0.06.tar.gz
KRAIH/nothing.tar.gz

# Archive::Tar extracts well on *nix, but not on Windows
GIRAFFED/Curses-1.18.tgz
GIRAFFED/Curses-1.25.tgz

# Even Archive::Tar extracts well
ANATRA/tbl2html-v1.1.tar.gz
ARDAN/historylogger.tar.gz
BCROWELL/LineByLine-1.0.tar.gz
BPRUDENT/VSS-1.0.3.tar.gz
BRADAPP/PodParser-1.02.tar.gz
BRTEAM/Batch-Batchrun-1.03.tar.gz
CDONLEY/NET-LDAPAPI-1.31.TAR.GZ
CEESHEK/CGI-Application-Plugin-Authentication-0.14.tar.gz
CHETANG/API-ReviewBoard-0.1.tar.gz
CHRISCHU/asm2htm-1.3.tar.gz
CHRISCHU/gif-info-1.1.tar.gz
COLINK/STATISTICS-DESCRIPTIVE-2.1.TAR.GZ
DAMBAR/Catalyst-Plugin-Imager-0.01.tar.gz
DARNOLD/DBD-Chart-0.74.tar.gz
DDUMONT/Puppet-LogBody-1.002.tar.gz
DDUMONT/RPC-Simple-0.1.tar.gz
DDUMONT/Text-Vpp-0.01.tar.gz
DOUGM/mod_perl-0.60a4.tar.gz
DRSTEVE/vimrc.tgz
ELEONORA/ptkbl_1.0.tar.gz
ESUMMERS/MARC-082.TGZ
FERNANDES/Ppa_json2ppa_csv.pl-0.01.tar.gz
FSG/PGP-1.0.tar.gz
GMG/WTweb-0.1.tar.gz
IANPX/Stem-0.1.tar.gz
IDIVISION/nginx-0.0.1.tar.gz
IDIVISION/nginx.pm.tar.gz
ITDEV/Tk-PlotDataset/Tk-PlotDataset-2.03.tar.gz
JEROMEMCK/ICQOn-1.6.tar.gz
JEROMEMCK/Net-ICQ-On-1.10.1.tar.gz
JEROMEMCK/Net-ICQ-On-1.10.2.tar.gz
JEROMEMCK/Net-ICQ-On-1.6.tar.gz
JEROMEMCK/Net-ICQ-On-1.7.tar.gz
JEROMEMCK/Net-ICQ-On-1.9.0.tar.gz
JEROMEMCK/Net-ICQ-On-1.9.1.tar.gz
JEROMEMCK/Net-ICQ-On-1.9.4.tar.gz
JOHAYEK/app-xlstar-1-36.tar.gz
JOSEPHW/XML-Writer-0.500.tar.gz
JOSEPHW/XML-Writer-0.510.tar.gz
JOSEPHW/XML-Writer-0.520.tar.gz
JOSEPHW/XML-Writer-0.530.tar.gz
JOSEPHW/XML-Writer-0.531.tar.gz
JOSEPHW/XML-Writer-0.540.tar.gz
JOSEPHW/XML-Writer-0.545.tar.gz
JOSEPHW/XML-Writer-0.600.tar.gz
JOSEPHW/XML-Writer-0.601.tar.gz
JSNBY/CDiso-1.0.0.2.tar.gz
KGJERDE/XPathToXML-0.01.tar.gz
LAXEN/BBDB-1.2.tar.gz
MANOJKG/makeManPg.tar.gz
MARSAB/Test123.pm.tar.gz
MELONMAN/EasyPDF_0_02.tgz
MFU/ToFroDos-1.00.tar.gz
MLFISHER/pmtools-1.10.tar.gz
MRAMBERG/Catalyst-5.67.tar.gz
NWINT/MD5-1.1.tar.gz
PARTICLE/testing-pause-upload-criteria-1.00.tar.gz
RCL/IPDevice-Allnet-ALL4000-0.10.tar.gz
RLAUGHLIN/UDPmsg-0.10.tar.gz
RLAUGHLIN/UDPmsg-0.11.tar.gz
SAULIUS/Date-Holidays-LT-0.01.tar.gz
SCHUBIGER/make2build-0.01_01.tar.gz
SCHUBIGER/make2build-0.01_02.tar.gz
SCHUBIGER/make2build-0.02.tar.gz
SCHUBIGER/make2build-0.03.tar.gz
SEOVISUAL/WebService-SEOmoz-FreeAPI-0.01.tar.gz
SHERZODR/Bundle-Config-Simple-0.01.tar.gz
TUSHAR/UniqueColumns_0.1.tar.gz
VLADB/cvs_init_1_01.tar.gz
VLADB/cvs_init_1_011.tar.gz
VLADB/cvs_init_1_01_.tar.gz
WIHAA/EPS-2.00.tar.gz
WINKO/BitCount-1.1.tar.gz
WINKO/Parext-1.1.tar.gz
WINKO/Parity-1.2.tar.gz
WSYVINSKI/Math-Vector-1.03.tar.gz
WSYVINSKI/Tie-TieConstant-1.01.tar.gz
YEWENBIN/deob-0.02.tar.gz

# Extracts differently
JEFFERY/Geo-MapInfo-MIF-0.01.tar.gz
MRAMBERG/Catalyst-Runtime-5.8000_05.tar.gz
SPIDB/Net-ext-0.77.tar.gz
SPIDB/Net-ext-0.78.tar.gz
SPIDB/net-ext-a8.tar.gz

# Can be extracted at least with /bin/tar
ADESC/DBD-Informix-0.20pl1.tar.gz
ADESC/DBD-Informix-0.22.tar.gz
ADESC/DBD-mSQL-0.60pl9.tar.gz
ADESC/Devel-CoreStack-1.3.tar.gz
ADESC/Informix/DBD-Informix-0.20pl0.tar.gz
ADESC/mSQL/DBD-mSQL-0.60pl7.tar.gz
ADESC/mSQL/DBD-mSQL-0.60pl8.tar.gz
ADESC/mSQL/DBD-mSQL-0.60pl9.tar.gz
AEPAGE/Devel-ptkdb-1.105.tar.gz
AEPAGE/Devel-ptkdb-1.1051.tar.gz
AEPAGE/Devel-ptkdb-1.1052.tar.gz
AEPAGE/ptkdb11.tar.gz
ALANSZ/Decision-Markov-0.01.tar.gz
ALSCH/Tk-SelFile-0.02.tar.gz
ANDK/Math-MatrixReal-1.1.tar.gz
ASANDSTRM/Unicode-Map8-0.06-bin-1-Mac.tgz
BARTLEY/Apache-AuthCookie-0.5.tar.gz
BARTLEY/Apache-AuthCookie-1.3.tar.gz
BBACKER/Perf-ARM-0.04.tar.gz
BDFOY/Business-ISBN-1.0.tar.gz
BIRNEY/bioperl-1.2.tar.gz
BKCHAPIN/DBIx-Perform-0.694.tar.gz
BLABES/DBIx-OracleSequence-0.03.tar.gz
BLABES/DBIx-OracleSequence-0.04.tar.gz
BMIDD/perl5.00402-bindist05-msvcAlpha.tar.gz
BPOWERS/Sybase-Login-1.2.tar.gz
BPOWERS/Tk-FileDialog-1.3.tar.gz
BRADAPP/PodFilter-0.01.tar.gz
BRADAPP/PodParser-1.00.tar.gz
BRADAPP/PodUsage-0.01.tar.gz
BROCSEIB/CGI-Cache-1.00.tar.gz
BROCSEIB/Tie-Syslog-1.02.tar.gz
BROCSEIB/Tie-Syslog-1.03.tar.gz
BWILLIAM/AltaVista-PerlSDK-3.02.tar.gz
BWILLIAM/AltaVista-SDKLinguistics-3.02.tar.gz
CAM/File-SetSize-0.1.tar.gz
CCOLBOURN/Text-StripAccents/Text-StripAccents-0.1.tar.gz
CCOLBOURN/ai-nnflex/AI-NNFlex-0.1.tar.gz
CCOLBOURN/ai-nnflex/AI-NNFlex-0.20.tar.gz
CCOLBOURN/ai-nnflex/AI-NNFlex-0.21.tar.gz
CCOLBOURN/ai-nnflex/ai-nnflex-0.1.tar.gz
CHAMAS/Apache-ASP-0.02.tar.gz
CHAMAS/Apache-ASP-0.03.tar.gz
CHARTGRP/Chart-2.2.tar.gz
CHLIGE/TAM-Admin-0.25.tar.gz
CHLIGE/TAM-Admin-0.3.tar.gz
CHLIGE/TAM-Admin-0.35.tar.gz
CHRWOLF/Msgcat-1.00.tar.gz
CHRWOLF/Msgcat-1.01.tar.gz
CKAISER/httpi-0.4.tar.gz
CKAISER/httpi-0.99.tar.gz
CKAISER/httpi-1.2.1.tar.gz
CKAISER/httpi-1.3.1.tar.gz
CKAISER/httpi-1.3.2.tar.gz
CKAISER/httpi-1.3.tar.gz
CKAISER/httpi-1.4.tar.gz
CKAISER/httpi-1.5.1.tar.gz
CKAISER/httpi-1.5.tar.gz
CKAISER/httpi-1.6.1.tar.gz
CKAISER/httpi-1.6.tar.gz
CKAISER/httpi-1.7.tar.gz
CTWETEN/Tie-SortHash-1.00.tar.gz
CTWETEN/Tie-SortHash-1.01.tar.gz
CTWETEN/override-1.01.tar.gz
CWHITE/HPUX-FS_0.01.tar.gz
CWHITE/HPUX-FS_0.02.tar.gz
CYK/Isam-0.2.tar.gz
DAVECROSS/Array-Compare-1.03.tar.gz
DAVECROSS/Tie-Hash-Regex-0.01.tar.gz
DAVIDH/Sub-Curry-0.07.tar.gz
DAVIDH/Sub-Curry-0.08.tar.gz
DDUMONT/Async-Group-0.2.tar.gz
DDUMONT/Async-Group-0.3.tar.gz
DDUMONT/Puppet-Any-0.01.tar.gz
DDUMONT/Puppet-Any-0.04.tar.gz
DDUMONT/Puppet-Body-1.012.tar.gz
DDUMONT/Puppet-Body-1.018.tar.gz
DDUMONT/Puppet-Log-1.010.tar.gz
DDUMONT/Puppet-Log-1.011.tar.gz
DDUMONT/Puppet-Show-1.002.tar.gz
DDUMONT/Puppet-Show-1.003.tar.gz
DDUMONT/Puppet-Show-1.005.tar.gz
DDUMONT/Puppet-Show-1.007.tar.gz
DDUMONT/Puppet-VcsTools-File-1.002.tar.gz
DDUMONT/Puppet-VcsTools-File-1.003.tar.gz
DDUMONT/Puppet-VcsTools-History-1.001.tar.gz
DDUMONT/Puppet-VcsTools-History-1.002.tar.gz
DDUMONT/Puppet-VcsTools-History-1.003.tar.gz
DDUMONT/Puppet-VcsTools-History-1.004.tar.gz
DDUMONT/RPC-Simple-0.2.tar.gz
DDUMONT/RPC-Simple-0.3.tar.gz
DDUMONT/Text-Vpp-0.02.tar.gz
DDUMONT/Text-Vpp-0.03.tar.gz
DDUMONT/Text-Vpp-0.04.tar.gz
DDUMONT/Text-Vpp-0.1.tar.gz
DDUMONT/Text-Vpp-0.2.tar.gz
DDUMONT/Text-Vpp-1.01.tar.gz
DDUMONT/Text-Vpp-1.1.tar.gz
DDUMONT/Text-Vpp-1.11.tar.gz
DDUMONT/Tk-Multi-0.01.tar.gz
DDUMONT/Tk-Multi-0.02.tar.gz
DDUMONT/Tk-Multi-0.03.tar.gz
DDUMONT/Tk-Multi-0.1.tar.gz
DDUMONT/Tk-Multi-0.2.tar.gz
DDUMONT/Tk-Multi-0.3.tar.gz
DDUMONT/Tk-Multi-0.4.tar.gz
DDUMONT/Tk-Multi-0.6.tar.gz
DDUMONT/Tk-Multi-0.72.tar.gz
DDUMONT/Tk-Multi-0.73.tar.gz
DDUMONT/Tk-Multi-0.80.tar.gz
DDUMONT/Tk-Multi-1.001.tar.gz
DDUMONT/Tk-Multi-1.002.tar.gz
DDUMONT/Tk-Multi-1.003.tar.gz
DDUMONT/Tk-ObjScanner-0.01.tar.gz
DDUMONT/Tk-ObjScanner-0.02.tar.gz
DDUMONT/Tk-ObjScanner-0.1.tar.gz
DDUMONT/Tk-ObjScanner-0.2.tar.gz
DDUMONT/Tk-ObjScanner-0.3.tar.gz
DDUMONT/Tk-ObjScanner-0.4.tar.gz
DDUMONT/Tk-ObjScanner-0.5.tar.gz
DDUMONT/Tk-ObjScanner-1.011.tar.gz
DDUMONT/Tk-ObjScanner-1.013.tar.gz
DDUMONT/Tk-ObjScanner-1.014.tar.gz
DDUMONT/Tk-ObjScanner-1.016.tar.gz
DDUMONT/Tk-ObjScanner-1.017.tar.gz
DDUMONT/Tk-TreeGraph-1.004.tar.gz
DDUMONT/Tk-TreeGraph-1.005.tar.gz
DDUMONT/VcsTools-0.01.tar.gz
DDUMONT/VcsTools-File-1.001.tar.gz
DDUMONT/VcsTools-File-1.002.tar.gz
DDUMONT/VcsTools-File-1.003.tar.gz
DDUMONT/VcsTools-File-1.004.tar.gz
DDUMONT/VcsTools-History-1.001.tar.gz
DDUMONT/VcsTools-History-1.002.tar.gz
DDUMONT/VcsTools-History-1.003.tar.gz
DDUMONT/VcsTools-History-1.004.tar.gz
DFRENCH/AIX-ODM-1.0.1.tar.gz
DFRENCH/AIX-ODM-1.0.2.tar.gz
DFRENCH/AIX-ODM-1.0.tar.gz
DOMIZIO/HTML-TableTiler-1.0.tar.gz
DOMIZIO/HTML-TableTiler-1.01.tar.gz
DOMIZIO/Text-MagicTemplate-1.0.tar.gz
DOMIZIO/Text-MagicTemplate-1.1.tar.gz
DOMIZIO/Text-MagicTemplate-1.2.tar.gz
DOMIZIO/Text-MagicTemplate-1.21.tar.gz
DOMIZIO/Text-MagicTemplate-1.22.tar.gz
DOMIZIO/Text-MagicTemplate-1.23.tar.gz
DOMIZIO/Text-MagicTemplate-1.31.tar.gz
DOMIZIO/Text-MagicTemplate-2.0.tar.gz
DOMIZIO/Text-MagicTemplate-2.01.tar.gz
DOMIZIO/Text-MagicTemplate-2.02.tar.gz
DOMIZIO/Text-MagicTemplate-2.03.tar.gz
DOMIZIO/Text-MagicTemplateX-HTML-1.0.tar.gz
DOMIZIO/Text-MagicTemplateX-HTML-1.01.tar.gz
DOMIZIO/Text-MagicTemplateX-HTML-1.02.tar.gz
DOUGM/Apache-Perl-contrib-042797.tar.gz
DOUGM/Apache-Perl-contrib-061197.tar.gz
DOUGM/Apache-Perl-contrib-062997.tar.gz
DOUGM/DCE-Perl-0.11.tar.gz
DOUGM/DCE-Perl-0.15.tar.gz
DOUGM/ExtUtils-Embed-1.12_02.tar.gz
DOUGM/ExtUtils-Embed-1.12_03.tar.gz
DOUGM/HTTPD-Tools-0.52.tar.gz
DOUGM/HTTPD-Tools-0.53.tar.gz
DOUGM/HTTPD-Tools-0.54.tar.gz
DOUGM/HTTPD-Tools-0.55.tar.gz
DOUGM/mod_perl-0.60a2.tar.gz
DOUGM/mod_perl-0.60a5.tar.gz
DOUGM/mod_perl-0.70b1.tar.gz
DOUGM/mod_perl-0.76b1.tar.gz
DOUGM/mod_perl-0.81.tar.gz
DOUGM/mod_perl-0.83_02.tar.gz
DOUGM/mod_perl-0.83_03.tar.gz
DOUGM/mod_perl-0.83_04.tar.gz
DOUGM/mod_perl-0.83_06.tar.gz
DOUGM/mod_perl-0.83_07.tar.gz
DOUGM/mod_perl-0.83_09.tar.gz
DOUGM/mod_perl-0.83_10.tar.gz
DOUGM/mod_perl-0.84.tar.gz
DOUGM/mod_perl-0.85.tar.gz
DOUGM/mod_perl-0.85_04.tar.gz
DOUGM/mod_perl-0.86.tar.gz
DOUGM/mod_perl-0.87.tar.gz
DOUGM/mod_perl-0.88.tar.gz
DOUGM/mod_perl-0.89.tar.gz
DOUGM/mod_perl-0.90_01.tar.gz
DOUGM/mod_perl-0.91.tar.gz
DOUGM/mod_perl-0.92.tar.gz
DOUGM/mod_perl-0.93_01.tar.gz
DOUGM/mod_perl-0.94.tar.gz
DOUGM/mod_perl-0.95_02.tar.gz
DOUGM/mod_perl-0.95_03.tar.gz
DOUGM/mod_perl-0.95_04.tar.gz
DOUGM/mod_perl-0.95_05.tar.gz
DOUGM/mod_perl-0.95_06.tar.gz
DOUGM/mod_perl-0.96.tar.gz
DOUGM/mod_perl-0.97.tar.gz
DOUGM/mod_perl-0.98_03.tar.gz
DOUGM/mod_perl-0.98_09.tar.gz
DOUGM/mod_perl-0.98_10.tar.gz
DOUGM/mod_perl-0.98_11.tar.gz
DOUGM/mod_perl-0.99.tar.gz
DOUGM/mod_perl-1.00b1.tar.gz
DOUGM/mod_perl-1.00b2.tar.gz
DOUGW/Convert-TNEF-0.05.tar.gz
DOUGW/Convert-TNEF-0.06.tar.gz
DOUGW/Convert-TNEF-0.07.tar.gz
DOUGW/Convert-TNEF-0.08.tar.gz
DOUGW/Parse-FixedLength-5.31.tar.gz
DROBERTS/File-Repl-0.4.tar.gz
DROBERTS/File-Repl0.4.tar.gz
EIJABB/MARC-Errorchecks-1.04.tar.gz
EIJABB/MARC-Errorchecks-1.05.tar.gz
EIJABB/MARC-Errorchecks-1.06.tar.gz
EIJABB/MARC-Errorchecks-1.08.tar.gz
EIJABB/MARC-Errorchecks-1.09.tar.gz
EIJABB/MARC-Errorchecks-1.13.tar.gz
EIJABB/MARC-Errorchecks-1.14.tar.gz
EIJABB/MARC-Lint-1.41.tar.gz
EIJABB/MARC-Lint-1.42.tar.gz
EIJABB/MARC-Lint-1.43.tar.gz
EIJABB/MARC-Lint-1.44.tar.gz
EIJABB/marc-lint-1.41.tar.gz
FMC/Sx-2.2.tar.gz
FPIVARI/GraphMaker-1.1.tar.gz
FPIVARI/GraphMaker-2.0.tar.gz
FPIVARI/GraphMaker-2.1.tar.gz
FPIVARI/pgphtml-1.0.tar.gz
FPIVARI/unpgphtml-1.0.tar.gz
FSORIANO/Tree-Nary-1.3.tar.gz
GBARR/FindBin-1.01.tar.gz
GBARR/MailTools-1.04.tar.gz
GENJISCH/Convert-Translit-1.00.tar.gz
GENJISCH/Convert-Translit-1.01.tar.gz
GENJISCH/Convert-Translit-1.02.tar.gz
GGONTER/hp200lx-0.1.tar.gz
GGONTER/hp200lx-0.2.tar.gz
GLOVER/Cdk-ext-4.7.0.tar.gz
GMLEWIS/RenderMan-0.02.tar.gz
GROMMEL/Acme-Turing-0.01.tar.gz
GROMMEL/Convert-IBM390-0.01.tar.gz
GROMMEL/Convert-IBM390-0.15.tar.gz
GROMMEL/Convert-IBM390-0.15X.tar.gz
GROMMEL/Convert-IBM390-0.18.tar.gz
GROMMEL/Convert-IBM390-0.19.tar.gz
GROMMEL/Convert-IBM390-0.25.tar.gz
GROMMEL/Convert-IBM390p-0.01.tar.gz
GROMMEL/MVS-VBFile-0.01.tar.gz
GROMMEL/MVS-VBFile-0.03.tar.gz
GROMMEL/MVS-VBFile-0.05.tar.gz
GROMMEL/Math-Random-0.62.tar.gz
GROMMEL/Math-Random-0.64.tar.gz
GROMMEL/Math-Random-0.65.tar.gz
GROMMEL/Math-Random-0.66.tar.gz
GROMMEL/Math-Round-0.01.tar.gz
GROMMEL/Math-Round-0.03.tar.gz
GROMMEL/Math-Round-0.04.tar.gz
GROMMEL/Math-Round-0.05.tar.gz
GROMMEL/Teradata-SQL-0.04.tar.gz
GROMMEL/Teradata-SQL-0.05.tar.gz
GROMMEL/Teradata-SQL-0.06.tar.gz
GSAR/Data-Dumper-1.22.tar.gz
HAWKINSM/IBM-LoadLeveler-0.07.tar.gz
HAWKINSM/IBM-LoadLeveler-1.03.tar.gz
HAWKINSM/IBM-LoadLeveler-1.04.tar.gz
HAWKINSM/LoadLeveler-0.05.tar.gz
HMBRAND/DBD-Unify-0.10.tar.gz
HMBRAND/DBD-Unify-0.11.tgz
HMBRAND/DBD-Unify-0.23.tgz
HMBRAND/DBD-Unify-0.24.tgz
HMBRAND/DBD-Unify-0.25.tgz
HMBRAND/DBD-Unify-0.42.tgz
HMBRAND/DBD-Unify-0.60.tgz
HMBRAND/DBD-Unify-0.61.tgz
HMBRAND/Test-Smoke-1.08.tgz
HMBRAND/Test-Smoke-1.11.tgz
HMBRAND/Text-OutputFilter-0.11.tgz
HMBRAND/Tk-Clock-0.05.tar.gz
HMBRAND/Tk-Clock-0.10.tgz
HMBRAND/Tk-Clock-0.11.tgz
HPALM/VRML-0.90.tar.gz
HPALM/VRML-0.91.tar.gz
HPALM/VRML-0.92.tar.gz
HPALM/VRML-0.97.tar.gz
HTOUG/DBD-Ingres-0.04.tar.gz
HTOUG/DBD-Ingres-0.05.tar.gz
HTOUG/DBD-Ingres-0.0504.tar.gz
HTOUG/DBD-Ingres-0.05_91.tar.gz
HTOUG/DBD-Ingres-0.05_92.tar.gz
HTOUG/DBD-Ingres-0.05_93.tar.gz
HTOUG/DBD-Ingres-0.05_96.tar.gz
HTOUG/DBD-Ingres-0.10.tar.gz
HTOUG/DBD-Ingres-0.11.tar.gz
HTOUG/DBD-Ingres-0.13.tar.gz
HTOUG/DBD-Ingres-0.14.tar.gz
HTOUG/DBD-Ingres-0.16.tar.gz
HTOUG/DBD-Ingres-0.19_1.tar.gz
HTOUG/DBD-Ingres-0.19_3.tar.gz
HTOUG/DBD-Ingres-0.20.tar.gz
HTOUG/DBD-Ingres-0.21.tar.gz
HTOUG/DBD-Ingres-0.22.tar.gz
HTOUG/DBD-Ingres-0.24.tar.gz
HTOUG/DBD-Ingres-0.25.tar.gz
HTOUG/DBD-Ingres-0.26.tar.gz
HTOUG/DBD-Ingres-0.27.tar.gz
HTOUG/DBD-Ingres-0.28.tar.gz
HTOUG/DBD-Ingres-0.29.tar.gz
HTOUG/DBD-Ingres-0.30.tar.gz
HTOUG/DBD-Ingres-0.31.tar.gz
HTOUG/DBD-Ingres-0.32.tar.gz
HTOUG/DBD-Ingres-0.36.tar.gz
HTOUG/DBD-Ingres-0.37.tar.gz
HTOUG/DBD-Ingres-0.38.tar.gz
HTOUG/DBD-Ingres-0.39.tar.gz
HTOUG/DBD-Ingres-0.51.tar.gz
IBMTORDB2/DBD-DB2-0.73.tar.gz
IBMTORDB2/DBD-DB2-0.76.tar.gz
IBMTORDB2/DBD-DB2-0.77.tar.gz
IBMTORDB2/DBD-DB2.0.77.tar.gz
IGUTHRIE/Filesys-Statvfs-0.43.tar.gz
IGUTHRIE/Filesys-Statvfs_Df-0.44.tar.gz
IGUTHRIE/Filesys-Statvfs_Df-0.45.tar.gz
IGUTHRIE/Filesys-Statvfs_Df-0.47.tar.gz
IGUTHRIE/Filesys-Statvfs_Df-0.49.tar.gz
IGUTHRIE/Filesys-Statvfs_Df-0.50.tar.gz
IGUTHRIE/Filesys-Statvfs_Df-0.52.tar.gz
IGUTHRIE/Filesys-Statvfs_Df-0.57.tar.gz
IGUTHRIE/Filesys-Statvfs_Df-0.61.tar.gz
IGUTHRIE/Filesys-Statvfs_Df-0.65.tar.gz
ILTZU/Tie-CharArray-0.02.tar.gz
ILTZU/Tie-CharArray-1.00.tar.gz
JACKS/IPC_SysV.tar.gz
JACKS/InitializeServer-1.0.tar.gz
JACKS/Prolog-alpha.tar.gz
JACKS/UNIVERSAL-1.0.tar.gz
JARIAALTO/Lingua-EN-Squeeze-1998.1204.tar.gz
JBUHACOFF/CGI-Session-BitBucket-1.1.tar.gz
JBUHACOFF/CGI-Session-BitBucket-1.2.tar.gz
JBUHACOFF/CGI-Session-Driver-bitbucket-1.06.tar.gz
JBUHACOFF/Data-SimplePaginator-0.3.tar.gz
JBUHACOFF/Data-SimplePaginator-0.5.tar.gz
JEDWARDS/PDL-IO-Grib-2.0.tar.gz
JEFFH/Apache-AuthenPasswdSrv-0.01.tar.gz
JHI/Acme-Ook-0.04.tar.gz
JHI/Acme-Ook-0.05.tar.gz
JHI/Acme-Ook-0.06.tar.gz
JHI/Acme-Ook-0.07.tar.gz
JHI/Acme-Ook-0.08.tar.gz
JHI/Acme-Ook-0.09.tar.gz
JHI/BSD-Resource-1.03.tar.gz
JHI/BSD-Resource-1.05.tar.gz
JHI/BSD-Resource-1.05_01.tar.gz
JHI/BSD-Resource-1.05_02.tar.gz
JHI/BSD-Resource-1.06.tar.gz
JHI/BSD-Resource-1.07.00.tar.gz
JHI/BSD-Resource-1.0701.tar.gz
JHI/BSD-Resource-1.09.tar.gz
JHI/BSD-Resource-1.10.tar.gz
JHI/BSD-Resource-1.11.tar.gz
JHI/BSD-Resource-1.15.tar.gz
JHI/BSD-Resource-1.17.tar.gz
JHI/BSD-Resource-1.18.tar.gz
JHI/BSD-Resource-1.19.tar.gz
JHI/BSD-Resource-1.21.tar.gz
JHI/BSD-Resource-1.22.tar.gz
JHI/BSD-Resource-1.23.tar.gz
JHI/BSD-Time-0.01.tar.gz
JHI/BSD-Time-0.02.tar.gz
JHI/BSD-Time-0.03.tar.gz
JHI/Class-Privacy-0.03.tar.gz
JHI/Graph-0.20102.tar.gz
JHI/Lingua-FI-Hyphenate-0.02.tar.gz
JHI/Lingua-FI-Hyphenate-0.03.tar.gz
JHI/Lingua-FI-Hyphenate-0.04.tar.gz
JHI/Lingua-FI-Kontti-0.01.tar.gz
JHI/Lingua-FI-Kontti-0.02.tar.gz
JHI/Lingua-FI-Transcribe-0.02.tar.gz
JHI/Lingua-FI-Transcribe-0.03.tar.gz
JHI/Regex-PreSuf-0.002.tar.gz
JHI/Regex-PreSuf-0.003.tar.gz
JHI/Regex-PreSuf-0.004.tar.gz
JHI/Regex-PreSuf-0.005.tar.gz
JHI/Regex-PreSuf-1.01.tar.gz
JHI/Regex-PreSuf-1.10.tar.gz
JHI/Regex-PreSuf-1.11.tar.gz
JHI/Regex-PreSuf-1.12.tar.gz
JHI/Set-Bag-1.001.tar.gz
JHI/Set-Bag-1.002.tar.gz
JHI/Set-Bag-1.004.tar.gz
JHI/Set-Bag-1.006.tar.gz
JHI/Set-Bag-1.007.tar.gz
JHI/Set-Bag-1.008.tar.gz
JHI/Set-Scalar-0.004.tar.gz
JHI/Set-Scalar-0.00401.tar.gz
JHI/Set-Scalar-1.01.tar.gz
JHI/Set-Scalar-1.02.tar.gz
JHI/Set-Scalar-1.03.tar.gz
JHI/Set-Scalar-1.04.tar.gz
JHI/Set-Scalar-1.05.tar.gz
JHI/Set-Scalar-1.06.tar.gz
JHI/Set-Scalar-1.07.tar.gz
JHI/Set-Scalar-1.08.tar.gz
JHI/Set-Scalar-1.09.tar.gz
JHI/Set-Scalar-1.10.tar.gz
JHI/Set-Scalar-1.11.tar.gz
JHI/Set-Scalar-1.12.tar.gz
JHI/Set-Scalar-1.16.tar.gz
JHI/Set-Scalar-1.17.tar.gz
JHI/Set-Scalar-1.18.tar.gz
JHI/Set-Scalar-1.19.tar.gz
JHI/Statistics-DEA-0.01.tar.gz
JHI/Statistics-Frequency-0.01.tar.gz
JHI/Statistics-Shannon-0.01.tar.gz
JHI/Statistics-Shannon-0.02.tar.gz
JHI/Statistics-Shannon-0.03.tar.gz
JHI/Statistics-Simpson-0.01.tar.gz
JHI/String-Approx-2.0.tar.gz
JHI/String-Approx-2.0_01.tar.gz
JHI/String-Approx-2.2.tar.gz
JHI/String-Approx-2.3.tar.gz
JHI/String-Approx-2.4.tar.gz
JHI/String-Approx-2.5.tar.gz
JHI/String-Approx-2.6.tar.gz
JHI/String-Approx-2.7.tar.gz
JHI/String-Approx-3.01.tar.gz
JHI/String-Approx-3.02.tar.gz
JHI/String-Approx-3.03.tar.gz
JHI/String-Approx-3.04.tar.gz
JHI/String-Approx-3.08.tar.gz
JHI/String-Approx-3.09.tar.gz
JHI/String-Approx-3.10.tar.gz
JHI/String-Approx-3.11.tar.gz
JHI/String-Approx-3.15.tar.gz
JHI/String-Approx-3.16.tar.gz
JHI/String-Approx-3.17.tar.gz
JHI/String-Approx-3.18.tar.gz
JHI/String-Approx-3.19.tar.gz
JHI/String-Approx-3.20.tar.gz
JHI/String-Approx-3.22.tar.gz
JHI/String-Scanf-2.0.tar.gz
JHI/Time-HiRes-1.31.tar.gz
JHI/Time-HiRes-1.34.tar.gz
JHI/Time-HiRes-1.56.tar.gz
JHOWELL/FAQ-OMatic-2.501.tar.gz
JHOWELL/FAQ-OMatic-2.602.tar.gz
JHOWELL/FAQ-OMatic-2.606.tar.gz
JHOWELL/FAQ-OMatic-2.609.tar.gz
JHOWELL/FAQ-OMatic-2.610.tar.gz
JHOWELL/FAQ-OMatic-2.611.tar.gz
JHOWELL/FAQ-OMatic-2.615.tar.gz
JIANGS/CaCORE-3.01.tar.gz
JIANGS/CaCORE-3.092.tar.gz
JMM/Heap-0.50.tar.gz
JONG/bio_lib.1.7.tar.gz
JONG/evalign.1.5.tar.gz
JONG/geanfammer.1.3.tar.gz
JONG/sc_rate_1.1.tar.gz
JONO/Statistics-ChiSquare-0.2.tar.gz
JPEACOCK/Math-Currency-0.08.tar.gz
JPEACOCK/Math-Currency-0.09.tar.gz
JPEACOCK/Math-FixedPrecision-0.02.tar.gz
JPEACOCK/Math-FixedPrecision-0.03.tar.gz
JPEACOCK/Math-FixedPrecision-0.04.tar.gz
JPEACOCK/Math-FixedPrecision-0.05.tar.gz
JPEACOCK/Math-FixedPrecision-0.06.tar.gz
JPEACOCK/Math-FixedPrecision-0.11.tar.gz
JPRAVETZ/pod2ps-1.0.1.tar.gz
KARLON/Chart-Pie-0.90.tar.gz
KGB/ExtUtils-F77-1.01.tar.gz
KGB/PGPLOT-2.0.tar.gz
KGB/PGPLOT-2.01.tar.gz
KGB/PGPLOT-2.02.tar.gz
KGB/PGPLOT-2.04.tar.gz
KGB/PGPLOT-2.06.tar.gz
KGB/PGPLOT1.0b_src.tar.gz
KWILLIAMS/Apache-Filter-0.01.tar.gz
KWILLIAMS/Apache-Filter-0.05.tar.gz
KWILLIAMS/Apache-Filter-0.06.tar.gz
KWILLIAMS/Apache-Filter-0.07.tar.gz
KWILLIAMS/Apache-Filter-0.08.tar.gz
KWILLIAMS/Apache-Filter-0.09.tar.gz
KWILLIAMS/Apache-Filter-0.10.tar.gz
KWILLIAMS/Apache-SSI-1.90.tar.gz
KWILLIAMS/Apache-SSI-1.91.tar.gz
KWILLIAMS/Apache-SSI-1.92.tar.gz
KWILLIAMS/Apache-SSI-1.94.tar.gz
KWILLIAMS/Apache-SSI-2.02.tar.gz
KWILLIAMS/Apache-SSI-2.04.tar.gz
KWILLIAMS/Apache-SSI-2.05.tar.gz
KWILLIAMS/File-Backup-0.01.tar.gz
KWILLIAMS/File-Backup-0.02.tar.gz
KWILLIAMS/HTML-SimpleParse-0.01.tar.gz
KWILLIAMS/HTML-SimpleParse-0.02.tar.gz
KWILLIAMS/HTML-SimpleParse-0.05.tar.gz
KWILLIAMS/HTML-SimpleParse-0.06.tar.gz
KWILLIAMS/Math-BaseCalc-1.007.tar.gz
KWILLIAMS/Taco-0.01.tar.gz
KWILLIAMS/Taco-0.02.tar.gz
KWILLIAMS/Taco-0.03.tar.gz
KWILLIAMS/Text-FillIn-0.01.tar.gz
KWILLIAMS/Text-FillIn-0.02.tar.gz
KWILLIAMS/Text-FillIn-0.03.tar.gz
KWILLIAMS/Text-FillIn-0.05.tar.gz
KWILLIAMS/Tie-DB_Lock-0.01.tar.gz
KWILLIAMS/Tie-DB_Lock-0.02.tar.gz
KWILLIAMS/Tie-DB_Lock-0.03.tar.gz
KWILLIAMS/Tie-DB_Lock-0.04.tar.gz
KWILLIAMS/Tie-DB_Lock-0.05.tar.gz
KWILLIAMS/Tie-LLHash-0.01.tar.gz
KWILLIAMS/Tie-LLHash-0.02.tar.gz
KWILLIAMS/Tie-LLHash-0.03.tar.gz
KWILLIAMS/Tie-TextDir-0.01.tar.gz
KWILLIAMS/Tie-TextDir-0.02.tar.gz
KWILLIAMS/Tie-TextDir-0.03.tar.gz
LBENDAVID/Net-Telnet-Brcd-0.19.tar.gz
LBENDAVID/Net-Telnet-Brcd-1.12.tar.gz
LINDNER/HTML-Clean-0.7.tar.gz
LUISMUNOZ/NetAddr-IP-2.24.tar.gz
LUSOL/Getopt-EvaP-2.3.1.tar.gz
LUSOL/Getopt-EvaP-2.3.2.tar.gz
LUSOL/Tie-Watch-0.92.tar.gz
LUSOL/Tie-Watch-0.94.tar.gz
LUSOL/Tie-Watch-0.95.tar.gz
LUSOL/Tie-Watch-0.97.tar.gz
MEWP/DBD-Sybase-0.01.tar.gz
MHM/DBD-DB2-0.63.tar.gz
MHM/DBD-DB2-0.64.tar.gz
MHM/DBD-DB2-0.69.tar.gz
MHM/DBD-DB2-0.70.tar.gz
MIKEDLR/Tie-TransactHash-0.01.tar.gz
MPIOTR/Lingua-Ident-1.0.tar.gz
MPIOTR/Locale-Iconv-0.01.tar.gz
MPIOTR/Text-Iconv-1.0.tar.gz
MPIOTR/Text-Iconv-1.1.tar.gz
MPIOTR/Text-Iconv-1.2.tar.gz
MPIOTR/User-Utmp-0.02.tar.gz
MPIOTR/User-Utmp-1.0.tar.gz
MPIOTR/User-Utmp-1.01.tar.gz
MPIOTR/User-Utmp-1.6.tar.gz
MSICKEL/geo-ecef-1.0.0.tar.gz
MUENALAN/Class-Maker-0.01.tar.gz
NI-S/Ptty-0.01.tar.gz
NI-S/Tk-JPEG-b11.tar.gz
NI-S/Tk-b8.tar.gz
NI-S/Tk-b9.01.tar.gz
NI-S/Tk-b9.tar.gz
NOG/rcsfreeze-1.7.tar.gz
NOG/rcsfreeze-1.8.tar.gz
NWINT/MD5-1.2.1.tar.gz
NWINT/MD5-1.5.3.tar.gz
NWINT/MD5-1.6.tar.gz
NWINT/MD5-1.7.tar.gz
NWRIGHT/GIFgraph-Boxplot-1.00.tar.gz
OESTERHOL/Term-Screen-ReadLine-0.33.tar.gz
OESTERHOL/Term-Screen-Wizard-0.20.tar.gz
OESTERHOL/Term-Screen-Wizard-0.45.tar.gz
OESTERHOL/Term-Screen-Wizard-0.46.tar.gz
OESTERHOL/Term-Screen-Wizard-0.47.tar.gz
OESTERHOL/Term-Screen-Wizard-0.48.tar.gz
OKAMOTO/MIME-Types-0.01.tar.gz
OKAMOTO/MIME-Types-0.02.tar.gz
OKAMOTO/MIME-Types-0.03.tar.gz
PAULG/Logfile-Rotate-0.07.tar.gz
PAULG/Logfile-Rotate-0.12.tar.gz
PAULG/Logfile-Rotate-1.03.tar.gz
PAYERLE/Net-Hesiod-1.10a.tar.gz
PAYERLE/Net-Hesiod-1.11.tar.gz
PFRANCEUS/LSF-Base-0.01.tar.gz
PFRANCEUS/LSF-Batch-0.01.tar.gz
PMQS/BerkDB-0.01.tar.gz
PMQS/BerkeleyDB-0.02.tar.gz
PMQS/Compress-Zlib-1.00.tar.gz
PMQS/Compress-Zlib-1.01.tar.gz
PMQS/DB_File-1.14.tar.gz
PMQS/DB_File-1.15.tar.gz
PMQS/DB_File-1.16.tar.gz
PMQS/DB_File-1.51Beta.tar.gz
PMQS/DB_File-1.57.tar.gz
PMQS/DB_File-1.58.tar.gz
PMQS/Filter-1.09.tar.gz
PMQS/Filter-1.10.tar.gz
PMQS/Filter-1.12.tar.gz
PMQS/Filter-1.13.tar.gz
PMQS/xsubpp-1.922.tar.gz
PRL/PCL-Simple-1.tar.gz
PRL/Term-Interact-0.40.tar.gz
PRL/Term-Interact-0.41.tar.gz
PRL/Term-Interact-0.42.tar.gz
PRL/Term-Interact-0.43.tar.gz
PRYAN/Period-1.11.tar.gz
PVERD/mop-1.06.tar.gz
PVHP/OS390-Stdio-0.003.tar.gz
PVHP/ptkFAQ-0_03.tar.gz
RAM/Storable-0.4@2.tar.gz
RAM/Storable-0.4@3.tar.gz
RAM/Storable-0.4@4.tar.gz
RAM/Storable-0.4@5.tar.gz
RAM/Storable-0.4@6.tar.gz
RAM/Storable-0.4@7.tar.gz
RAM/Storable-0.5@2.tar.gz
RAM/Storable-0.5@3.tar.gz
RAM/Storable-0.5@5.tar.gz
RAM/Storable-0.5@6.tar.gz
RAM/Storable-0.6@0.tar.gz
RAM/Storable-0.6@1.tar.gz
RAM/Storable-0.6@2.tar.gz
RAM/cshar-3.0@15.tar.gz
RAM/kit-2.0@34.tar.gz
RGIERSIG/IO-Tty-0.05.tar.gz
RGIERSIG/IO-Tty-1.03.tar.gz
RJRAY/Devel-Coverage-0.1.tar.gz
RJRAY/Image-Size-1.0.tar.gz
RJRAY/Image-Size-1.1.tar.gz
RJRAY/Image-Size-1.2.tar.gz
RJRAY/Image-Size-2.0.tar.gz
RJRAY/Image-Size-2.1.tar.gz
RJRAY/Image-Size-2.2.tar.gz
RJRAY/Image-Size-2.3.tar.gz
RJRAY/Image-Size-2.4.tar.gz
RJRAY/Image-Size-2.5.tar.gz
RJRAY/X11-Fvwm-0.1.tar.gz
RJRAY/X11-Fvwm-0.2.tar.gz
RJRAY/X11-Fvwm-0.4.tar.gz
RJRAY/X11-Fvwm-1.0.tar.gz
RKHILL/Astro-Sunrise-0.0201.tar.gz
RKHILL/Astro-Sunrise-0.03.tar.gz
SAMPO/Net_SSLeay.pm-0.04.tar.gz
SBALA/jperl_beta_r1.tar.gz
SBURKE/Array-Autojoin-0.01.tar.gz
SBURKE/Array-Autojoin-0.02.tar.gz
SBURKE/Class-BlackHole-0.02.tar.gz
SBURKE/Class-BlackHole-0.03.tar.gz
SBURKE/Class-Classless-0.25.tar.gz
SBURKE/Class-Classless-1.21.tar.gz
SBURKE/Class-Classless-1.22.tar.gz
SBURKE/Class-Classless-1.33.tar.gz
SBURKE/Class-ISA-0.2.tar.gz
SBURKE/Class-ISA-0.32.tar.gz
SBURKE/Games-Dissociate-0.12.tar.gz
SBURKE/Games-Dissociate-0.13.tar.gz
SBURKE/Games-Worms-0.60.tar.gz
SBURKE/Games-Worms-Tk-0.41.tar.gz
SBURKE/Getopt-constant-1.01.tar.gz
SBURKE/Getopt-constant-1.02.tar.gz
SBURKE/HTML-Tagset-3.01.tar.gz
SBURKE/HTML-Tagset-3.02.tar.gz
SBURKE/HTML-Tagset-3.03.tar.gz
SBURKE/HTML-Tree-0.61.tar.gz
SBURKE/HTML-Tree-0.65.tar.gz
SBURKE/HTML-Tree-0.68.tar.gz
SBURKE/HTML-Tree-3.05.tar.gz
SBURKE/HTML-Tree-3.06.tar.gz
SBURKE/HTML-Tree-3.07.tar.gz
SBURKE/HTML-Tree-3.1.tar.gz
SBURKE/HTML-Tree-3.11.tar.gz
SBURKE/HTML-Tree-3.12.tar.gz
SBURKE/HTML-Tree-3.13.tar.gz
SBURKE/I18N-LangTags-0.23.tar.gz
SBURKE/I18N-LangTags-0.24.tar.gz
SBURKE/I18N-LangTags-0.26.tar.gz
SBURKE/I18N-LangTags-0.27.tar.gz
SBURKE/IO-Null-0.02.tar.gz
SBURKE/Lingua-EN-Numbers-Ordinate-0.01.tar.gz
SBURKE/Locale-Maketext-0.17.tar.gz
SBURKE/Locale-Maketext-1.01.tar.gz
SBURKE/Locale-Maketext-1.02.tar.gz
SBURKE/Locale-Maketext-1.03.tar.gz
SBURKE/MIDI-Perl-0.71.tar.gz
SBURKE/MIDI-Perl-0.77.tar.gz
SBURKE/MIDI-Perl-0.78.tar.gz
SBURKE/MIDI-Perl-0.79.tar.gz
SBURKE/Mac-FileSpec-Unixish-1.1.tar.gz
SBURKE/Mac-FileSpec-Unixish-1.11.tar.gz
SBURKE/Mac-RecentDocuments-0.01.tar.gz
SBURKE/Pod-Escapes-1.02.tar.gz
SBURKE/Pod-Escapes-1.03.tar.gz
SBURKE/Pod-HTML2Pod-4.03.tar.gz
SBURKE/RTF-Writer-1.06.tar.gz
SBURKE/Sort-ArbBiLex-3.1.tar.gz
SBURKE/Sort-ArbBiLex-3.11.tar.gz
SBURKE/Sort-ArbBiLex-3.21.tar.gz
SBURKE/Sort-ArbBiLex-3.31.tar.gz
SBURKE/Sort-ArbBiLex-3.32.tar.gz
SBURKE/Sort-ArbBiLex-3.4.tar.gz
SBURKE/Test-1.21.tar.gz
SBURKE/Test-1.22.tar.gz
SBURKE/Tree-DAG_Node-0.75.tar.gz
SBURKE/Tree-DAG_Node-1.03.tar.gz
SBURKE/Tree-DAG_Node-1.04.tar.gz
SBURKE/strict-ModuleName-0.03.tar.gz
SCOTTZED/Bio-SAGE-Comparison-1.00.tar.gz
SCOTTZED/Bio-SAGE-DataProcessing-1.10.tar.gz
SCRESTO/Sys-MemInfo-0.4.tar.gz
SDOWD/POP3Client-1_16.tar.gz
SKUNZ/perlmenu.v3.3.tar.gz
SKUNZ/perlmenu.v4.0.tar.gz
SLEONOV/AIX-SysInfo-1.1.1.tar.gz
SLEONOV/AIX-SysInfo-1.1.tar.gz
SLEONOV/AIX-SysInfo-1.2.tar.gz
SPIDB/Net-ext-0.74.tar.gz
SPIDB/Net-ext-0.75.tar.gz
SPIDB/Net-ext-0.79.tar.gz
SPIDB/Net-ext-0.80.tar.gz
SPIDB/Net-ext-0.81.tar.gz
SPIDB/Net-ext-0.83.tar.gz
SPIDB/Net-ext-0.84.tar.gz
SPIDB/Net-ext-0.91.tar.gz
SPIDB/Net-ext-0.933.tar.gz
SREZIC/Netscape-Cache-0.2.tar.gz
STBEY/Bit-ShiftReg-2.0.tar.gz
STBEY/Bit-Vector-4.0.tar.gz
STBEY/Bit-Vector-4.1.tar.gz
STBEY/Bit-Vector-4.2.tar.gz
STBEY/Bit-Vector-5.0b1.tar.gz
STBEY/BitOps-ROL_ROR-2.0.tar.gz
STBEY/Data-Locations-3.0.tar.gz
STBEY/Data-Locations-4.3.tar.gz
STBEY/DateCalc-1.2a.tar.gz
STBEY/DateCalc-1.5.tar.gz
STBEY/DateCalc-2.1.tar.gz
STBEY/DateCalc-2.3.tar.gz
STBEY/DateCalc-3.0.tar.gz
STBEY/Graph-Kruskal-2.0.tar.gz
STBEY/Locations-1.0.tar.gz
STBEY/Math-MatrixBool-5.7.tar.gz
STBEY/Math-MatrixReal-1.0.tar.gz
STBEY/Math-MatrixReal-1.1.tar.gz
STBEY/Math-MatrixReal-1.2.tar.gz
STBEY/ROL_ROR-1.0.tar.gz
STBEY/ROL_ROR-1.1.tar.gz
STBEY/Set-IntegerFast-1.0.tar.gz
STBEY/Set-IntegerFast-2.0.tar.gz
STBEY/Set-IntegerFast-3.0.tar.gz
STBEY/Set-IntegerFast-3.2.tar.gz
STBEY/Set-IntegerFast-4.2.tar.gz
STBEY/Set-IntegerRange-4.2.tar.gz
STBEY/Tie-Handle-1.0.tar.gz
STBEY/Tie-Handle-2.0.tar.gz
STBEY/Tie-Handle-2.1.tar.gz
STBEY/Tie-Handle-3.0.tar.gz
STBEY/cartoons-1.0.tar.gz
STLACY/HTML-Table-0.90.tar.gz
TAYERS/Algorithm-LUHN-0.10.tar.gz
TAYERS/Algorithm-LUHN-1.00.tar.gz
TAYERS/Business-CINS-1.10.tar.gz
TAYERS/Business-CINS-1.11.tar.gz
TAYERS/Business-CINS-1.12.tar.gz
TAYERS/Business-CINS-1.13.tar.gz
TAYERS/Business-CUSIP-0.01.tar.gz
TAYERS/Business-CUSIP-1.01.tar.gz
TAYERS/Business-CUSIP-1.02.tar.gz
TAYERS/Business-SEDOL-1.01.tar.gz
TAYERS/Business-SEDOL-1.02.tar.gz
TAYERS/List-Intersperse-1.00.tar.gz
TGUMMELS/File-MkTemp-1.0.1.tar.gz
TGUMMELS/File-MkTemp-1.0.2.tar.gz
TGUMMELS/File-MkTemp-1.0.3.tar.gz
TGUMMELS/File-MkTemp-1.0.4.tar.gz
TGUMMELS/File-MkTemp-1.0.5.tar.gz
TGUMMELS/File-MkTemp-1.0.6.tar.gz
TIMB/DBI/DBI-0.64.tar.gz
TOMC/modules/Date-GetDate-2.00.tar.gz
TOMZO/Quota-0.1a.tar.gz
TRIAS/Fame-2.0c.tar.gz
TRIAS/Fame-2.0d.tar.gz
TRIAS/Fame-2.tar.gz
TSTANLEY/Config-Yacp-1.00.tar.gz
TSTANLEY/Config-Yacp-1.1.tar.gz
TSTANLEY/Games-QuizTaker-1.03.tar.gz
TSTANLEY/Games-QuizTaker-1.08.tar.gz
TSTANLEY/Games-QuizTaker-1.tar.gz
TSTANLEY/Logger-Simple-1.01.tar.gz
TSTANLEY/Logger-Simple-1.02.tar.gz
TSTANLEY/Logger-Simple-1.03.tar.gz
TSTANLEY/Logger-Simple-1.04.tar.gz
TSTANLEY/Logger-Simple-1.05.tar.gz
TSTANLEY/Logger-Simple-1.06.tar.gz
TSTANLEY/Logger-Simple-1.07.tar.gz
TSTANLEY/Logger-Simple-1.08.tar.gz
TSTANLEY/Logger-Simple-1.081.tar.gz
ULPFR/Logfile-0.112.tar.gz
ULPFR/Logfile-0.113.tar.gz
ULPFR/Math-Approx-0.1.tar.gz
ULPFR/Math-Mathematica-1.0.4.tar.gz
ULPFR/Math-Mathematica-1.0.5.tar.gz
ULPFR/Math-Matrix-0.1.tar.gz
ULPFR/Math-Matrix-0.2.tar.gz
ULPFR/Net-Country-0.1.tar.gz
ULPFR/Pconvert-1.04.tar.gz
ULPFR/Text-German-0.03.tar.gz
ULPFR/Wais-2.0.11.tar.gz
ULPFR/Wais-2.1.0.tar.gz
ULPFR/Wais-2.116.tar.gz
ULPFR/perlindex-1.107.tar.gz
