use strict;
use warnings;
use Test::More;

plan skip_all => 'todo';

done_testing;

__DATA__
# implausibly old time stamp
A/AS/ASANDSTRM/XML-Parser-2.26-bin-1-MacOS.tgz

# Cannot mknod: Operation not permitted
B/BP/BPORTER/ngbbs/ngbbs-0.1.6.tar.bz2

# not look like a tar archive
C/CA/CAPOEIRAB/WWW-Salesforce-0.03.tar.gz
C/CA/CAPOEIRAB/WWW-Salesforce-0.04.tar.gz
C/CA/CAPOEIRAB/WWW-Salesforce-Simple-0.07.tar.gz
C/CL/CLCL/WebService-KuronekoYamato-v0.0.4.tar.gz
C/CL/CLCL/WebService-NiigataUnyu-v0.0.1.tar.gz
C/CL/CLCL/WebService-NiigataUnyu-v0.0.3.tar.gz
C/CL/CLCL/WebService-SagawaKyubin-0.0.1.tar.gz
C/CL/CLCL/WebService-SagawaKyubin-v0.0.2.tar.gz
C/CL/CLCL/WebService-SagawaKyubin-v0.0.3.tar.gz
D/DA/DAZJORZ/Term-Prompt-0.05.tar.gz
D/DA/DAZJORZ/term-prompt-0.05.tar.gz
D/DC/DCANTRELL/Tie-Hash-Longest-1.0.reupload.tar.gz
D/DC/DCANTRELL/Tie-Hash-Longest-1.0.tar.gz
D/DR/DRBEAN/Games-Tournament-Swiss-004/tables-0.04.tar.gz
F/FR/FREMAN/Device-Inverter-Aurora.0.01.tar.gz
G/GE/GENE/Chess-Coverage-0.0101.tar.gz
G/GE/GENE/Chess-Coverage-0.03.tar.gz
I/IL/ILYAZ/modules/Math-Pari-2.0305_01080604.tar.gz
J/JJ/JJONES/SMS-Send-UK-Kapow-0.03.tar.gz
K/KH/KHW/Unicode-Casing-09.tar.gz
K/KO/KORSANI/Log-Funlog-0.88.tar.gz
K/KO/KORSANI/Log-Funlog-0.89.tar.gz
L/LB/LBENDAVID/DBD-TSM-0.12.tar.gz
L/LB/LBENDAVID/DBD-TSM/DBD-TSM-0.11.tar.gz
M/MA/MANOWAR/RadiusPerl-0.07.tar.gz
N/NY/NYAKNYAN/HTTP-Server-EV-0.21.tar.gz
P/PE/PETERGAL/PGForth1.1.tar.gz
P/PY/PYTHIAN/DBD-Oracle-1.24.tar.gz
S/SM/SMUELLER/PAR-0.953.tar.gz
T/TL/TLINDEN/WWW-Dict-Leo-Org-1.32.tar.gz

# unexpected end of file
C/CH/CHRMUE/Socket-Class-2.14.tar.gz
C/CL/CLKAO/SVK-v2.0.0_91.tar.gz
C/CN/CNANDOR/Compress-Zlib-1.01-bin-1-MacOS.tar.gz
D/DA/DAGOLDEN/Module-Build-0.34_03.tar.gz
J/JE/JESSE/RT-OnlineDocs-0.04.tar.gz
M/MA/MARTINB/Xforms4Perl-0.8.4-2.tgz
M/MS/MSCHILLI/Sysadm-Install-0.26.tar.gz
S/SA/SATOH/List-Enumerator-0.06.tar.gz

# compress: Cannot exec: No such file or directory
D/DA/DAUNAY/oEdtk.20070321.v0.31.tar.gz
I/IL/ILYAZ/etext/etext0.6.0.tar.gz
I/IL/ILYAZ/etext0.6.0.tar.gz
M/MA/MARCLANG/ParallelUserAgent-2.37.tar.gz
O/OW/OWEN/Math-RPN-1.03.tar.gz
O/OW/OWEN/Math-RPN-1.05.tar.gz
S/SC/SCHOEN/R3-0.01.tar.gz
S/SC/SCHOEN/R3-conn-0.20.tar.gz
S/SC/SCHOEN/R3-func-0.20.tar.gz
S/SC/SCHOEN/R3-itab-0.20.tar.gz
S/SC/SCHOEN/R3-rfcapi-0.20.tar.gz
S/SC/SCHOEN/R3-rfcapi-0.21.tar.gz

# Cannot open: File exists
H/HO/HOOO/X3D-0.00.1.tar.gz
Y/YE/YEWEI/test.tgz

# gzip: stdin: decompression OK, trailing garbage ignored
J/JA/JACKS/Usage-beta.tar.gz

# gzip: stdin: invalid compressed data--format violated
J/JC/JCAMACHO/Catalyst-Controller-FormBuilder-0.01_01.tar.gz

# tar: Skipping to next header
J/JH/JHARDING/aol-toc-0.3.tar.gz

# Cannot open: No such file or directory
L/LE/LEMBARK/Schedule-Depend-0.08.tar.gz
L/LE/LEMBARK/Schedule-Depend-0.27.tar.gz

# tar: Unexpected EOF in archive
X/XY/XYF/C3000-0.0052.tar.gz

# ZIP
A/AF/AFRYER/TUXEDO-1_00.zip
A/AM/AMGARLAND/DirFiles_1_0.zip
A/AS/ASTILLER/DBD_RDB-1_13.ZIP
A/AS/ASTILLER/DBD_RDB-1_14.ZIP
A/AS/ASTILLER/DBD_RDB-1_15.ZIP
A/AT/ATIFK/nmrwdog-0.1.zip
B/BY/BYOURTH/Math.SimpleInterest.0.02.ZIP
B/BY/BYOURTH/Math.SimpleInterest.0.03.ZIP
B/BY/BYOURTH/Math.SimpleInterest.0.04.ZIP
D/DA/DAVEROTH/Win32-API-Prototype/Win32-API-Prototype_AllBuilds.Zip
D/DS/DSUGAL/VMS-MISC-1_00.ZIP
F/FE/FERNANDES/155.zip
F/FE/FERNANDES/Reduziguais.zip
F/FG/FGLOCK/Myfile-0.01.zip
G/GS/GSLONDON/iperl.20040205.zip
I/IL/ILYAZ/os2/perl5.00301.os2.zip
J/JB/JBAKER/Apache-Session-0.10.zip
J/JB/JBAKER/mod_perl-1.07_04-bin-bindist1-i386-win32-vc5.zip
J/JO/JOCASA/futils.02Jun96.zip
K/KU/KULCHENKO/SOAP-Lite-0.55.zip
M/MA/MAKAROW/DBIx-Web-0.60a.tar.zip
M/MA/MAKAROW/DBIx-Web-0.62a.tar.zip
N/NR/NREICHEN/eicndhcpd_11.zip
N/NR/NREICHEN/eicndhcpd_v11_src.ZIP
P/PA/PAUL/Foo-0.0.1-beta1.zip
P/PH/PHOENIXL/extensible_report_generator_1.12.zip
P/PH/PHOENIXL/extensible_report_generator_1.13.zip
P/PT/PTILL/mod_perl-1.11_1-apache-1.3b7dev-bin-bindist1-i386-win95-vc5.zip
R/RI/RICHARDC/testmy-cgi-v.1.zip
R/RI/RICHARDC/testmycgi-v.1.zip
R/RI/RICHARDC/testmycgi-v0.1.zip
R/RJ/RJE/BURL-0.5.zip
R/RJ/RJE/UWP-0.8.zip
R/RJ/RJSRI/QXP-Validate-1.0.zip
R/RO/ROOTKWOK/Win32-SysPrivilege-v0.02.zip
R/RU/RURBAN/perlhlp.zip
S/SC/SCHUBIGER/scripts/newsletter-1.4.zip
S/SC/SCHUBIGER/scripts/newsletter-1.5.zip
S/SC/SCHUBIGER/scripts/newsletter-1.6.zip
S/SC/SCHUBIGER/scripts/newsletter-1.7.zip
S/SC/SCHWA/FFI-1.04-dll.zip
S/SN/SNEEX/HTML_Month.v6a.zip
S/SN/SNEEX/Post_FormMail.zip
V/VL/VLADB/cvs_init_1_01.zip
W/WA/WARTHURT/Memo32-1.00.zip



# Can be extracted at least with /bin/tar but Archive::Tar reveals serious issue

# mknod: Operation failed
A/AN/ANGERSTEI/Net-Ping-Network-1.55.tar.gz

# Can't call method list_files
A/AN/ANGERSTEI/Net-Ping-Network-1.57.tar.gz
B/BR/BROWSERUK/Used/Used-0.01.tar.gz
C/CH/CHIA/Regexp-Tr-0.06.tar.gz
K/KR/KRAIH/nothing.tar.gz

# Archive::Tar extracts well on *nix, but not on Windows
G/GI/GIRAFFED/Curses-1.18.tgz
G/GI/GIRAFFED/Curses-1.25.tgz

# Even Archive::Tar extracts well
A/AN/ANATRA/tbl2html-v1.1.tar.gz
A/AR/ARDAN/historylogger.tar.gz
B/BC/BCROWELL/LineByLine-1.0.tar.gz
B/BP/BPRUDENT/VSS-1.0.3.tar.gz
B/BR/BRADAPP/PodParser-1.02.tar.gz
B/BR/BRTEAM/Batch-Batchrun-1.03.tar.gz
C/CD/CDONLEY/NET-LDAPAPI-1.31.TAR.GZ
C/CE/CEESHEK/CGI-Application-Plugin-Authentication-0.14.tar.gz
C/CH/CHETANG/API-ReviewBoard-0.1.tar.gz
C/CH/CHRISCHU/asm2htm-1.3.tar.gz
C/CH/CHRISCHU/gif-info-1.1.tar.gz
C/CO/COLINK/STATISTICS-DESCRIPTIVE-2.1.TAR.GZ
D/DA/DAMBAR/Catalyst-Plugin-Imager-0.01.tar.gz
D/DA/DARNOLD/DBD-Chart-0.74.tar.gz
D/DD/DDUMONT/Puppet-LogBody-1.002.tar.gz
D/DD/DDUMONT/RPC-Simple-0.1.tar.gz
D/DD/DDUMONT/Text-Vpp-0.01.tar.gz
D/DO/DOUGM/mod_perl-0.60a4.tar.gz
D/DR/DRSTEVE/vimrc.tgz
E/EL/ELEONORA/ptkbl_1.0.tar.gz
E/ES/ESUMMERS/MARC-082.TGZ
F/FE/FERNANDES/Ppa_json2ppa_csv.pl-0.01.tar.gz
F/FS/FSG/PGP-1.0.tar.gz
G/GM/GMG/WTweb-0.1.tar.gz
I/IA/IANPX/Stem-0.1.tar.gz
I/ID/IDIVISION/nginx-0.0.1.tar.gz
I/ID/IDIVISION/nginx.pm.tar.gz
I/IT/ITDEV/Tk-PlotDataset/Tk-PlotDataset-2.03.tar.gz
J/JE/JEROMEMCK/ICQOn-1.6.tar.gz
J/JE/JEROMEMCK/Net-ICQ-On-1.10.1.tar.gz
J/JE/JEROMEMCK/Net-ICQ-On-1.10.2.tar.gz
J/JE/JEROMEMCK/Net-ICQ-On-1.6.tar.gz
J/JE/JEROMEMCK/Net-ICQ-On-1.7.tar.gz
J/JE/JEROMEMCK/Net-ICQ-On-1.9.0.tar.gz
J/JE/JEROMEMCK/Net-ICQ-On-1.9.1.tar.gz
J/JE/JEROMEMCK/Net-ICQ-On-1.9.4.tar.gz
J/JO/JOHAYEK/app-xlstar-1-36.tar.gz
J/JO/JOSEPHW/XML-Writer-0.500.tar.gz
J/JO/JOSEPHW/XML-Writer-0.510.tar.gz
J/JO/JOSEPHW/XML-Writer-0.520.tar.gz
J/JO/JOSEPHW/XML-Writer-0.530.tar.gz
J/JO/JOSEPHW/XML-Writer-0.531.tar.gz
J/JO/JOSEPHW/XML-Writer-0.540.tar.gz
J/JO/JOSEPHW/XML-Writer-0.545.tar.gz
J/JO/JOSEPHW/XML-Writer-0.600.tar.gz
J/JO/JOSEPHW/XML-Writer-0.601.tar.gz
J/JS/JSNBY/CDiso-1.0.0.2.tar.gz
K/KG/KGJERDE/XPathToXML-0.01.tar.gz
L/LA/LAXEN/BBDB-1.2.tar.gz
M/MA/MANOJKG/makeManPg.tar.gz
M/MA/MARSAB/Test123.pm.tar.gz
M/ME/MELONMAN/EasyPDF_0_02.tgz
M/MF/MFU/ToFroDos-1.00.tar.gz
M/ML/MLFISHER/pmtools-1.10.tar.gz
M/MR/MRAMBERG/Catalyst-5.67.tar.gz
N/NW/NWINT/MD5-1.1.tar.gz
P/PA/PARTICLE/testing-pause-upload-criteria-1.00.tar.gz
R/RC/RCL/IPDevice-Allnet-ALL4000-0.10.tar.gz
R/RL/RLAUGHLIN/UDPmsg-0.10.tar.gz
R/RL/RLAUGHLIN/UDPmsg-0.11.tar.gz
S/SA/SAULIUS/Date-Holidays-LT-0.01.tar.gz
S/SC/SCHUBIGER/make2build-0.01_01.tar.gz
S/SC/SCHUBIGER/make2build-0.01_02.tar.gz
S/SC/SCHUBIGER/make2build-0.02.tar.gz
S/SC/SCHUBIGER/make2build-0.03.tar.gz
S/SE/SEOVISUAL/WebService-SEOmoz-FreeAPI-0.01.tar.gz
S/SH/SHERZODR/Bundle-Config-Simple-0.01.tar.gz
T/TU/TUSHAR/UniqueColumns_0.1.tar.gz
V/VL/VLADB/cvs_init_1_01.tar.gz
V/VL/VLADB/cvs_init_1_011.tar.gz
V/VL/VLADB/cvs_init_1_01_.tar.gz
W/WI/WIHAA/EPS-2.00.tar.gz
W/WI/WINKO/BitCount-1.1.tar.gz
W/WI/WINKO/Parext-1.1.tar.gz
W/WI/WINKO/Parity-1.2.tar.gz
W/WS/WSYVINSKI/Math-Vector-1.03.tar.gz
W/WS/WSYVINSKI/Tie-TieConstant-1.01.tar.gz
Y/YE/YEWENBIN/deob-0.02.tar.gz

# Extracts differently
J/JE/JEFFERY/Geo-MapInfo-MIF-0.01.tar.gz
M/MR/MRAMBERG/Catalyst-Runtime-5.8000_05.tar.gz
S/SP/SPIDB/Net-ext-0.77.tar.gz
S/SP/SPIDB/Net-ext-0.78.tar.gz
S/SP/SPIDB/net-ext-a8.tar.gz

# Can be extracted at least with /bin/tar
A/AD/ADESC/DBD-Informix-0.20pl1.tar.gz
A/AD/ADESC/DBD-Informix-0.22.tar.gz
A/AD/ADESC/DBD-mSQL-0.60pl9.tar.gz
A/AD/ADESC/Devel-CoreStack-1.3.tar.gz
A/AD/ADESC/Informix/DBD-Informix-0.20pl0.tar.gz
A/AD/ADESC/mSQL/DBD-mSQL-0.60pl7.tar.gz
A/AD/ADESC/mSQL/DBD-mSQL-0.60pl8.tar.gz
A/AD/ADESC/mSQL/DBD-mSQL-0.60pl9.tar.gz
A/AE/AEPAGE/Devel-ptkdb-1.105.tar.gz
A/AE/AEPAGE/Devel-ptkdb-1.1051.tar.gz
A/AE/AEPAGE/Devel-ptkdb-1.1052.tar.gz
A/AE/AEPAGE/ptkdb11.tar.gz
A/AL/ALANSZ/Decision-Markov-0.01.tar.gz
A/AL/ALSCH/Tk-SelFile-0.02.tar.gz
A/AN/ANDK/Math-MatrixReal-1.1.tar.gz
A/AS/ASANDSTRM/Unicode-Map8-0.06-bin-1-Mac.tgz
B/BA/BARTLEY/Apache-AuthCookie-0.5.tar.gz
B/BA/BARTLEY/Apache-AuthCookie-1.3.tar.gz
B/BB/BBACKER/Perf-ARM-0.04.tar.gz
B/BD/BDFOY/Business-ISBN-1.0.tar.gz
B/BI/BIRNEY/bioperl-1.2.tar.gz
B/BK/BKCHAPIN/DBIx-Perform-0.694.tar.gz
B/BL/BLABES/DBIx-OracleSequence-0.03.tar.gz
B/BL/BLABES/DBIx-OracleSequence-0.04.tar.gz
B/BM/BMIDD/perl5.00402-bindist05-msvcAlpha.tar.gz
B/BP/BPOWERS/Sybase-Login-1.2.tar.gz
B/BP/BPOWERS/Tk-FileDialog-1.3.tar.gz
B/BR/BRADAPP/PodFilter-0.01.tar.gz
B/BR/BRADAPP/PodParser-1.00.tar.gz
B/BR/BRADAPP/PodUsage-0.01.tar.gz
B/BR/BROCSEIB/CGI-Cache-1.00.tar.gz
B/BR/BROCSEIB/Tie-Syslog-1.02.tar.gz
B/BR/BROCSEIB/Tie-Syslog-1.03.tar.gz
B/BW/BWILLIAM/AltaVista-PerlSDK-3.02.tar.gz
B/BW/BWILLIAM/AltaVista-SDKLinguistics-3.02.tar.gz
C/CA/CAM/File-SetSize-0.1.tar.gz
C/CC/CCOLBOURN/Text-StripAccents/Text-StripAccents-0.1.tar.gz
C/CC/CCOLBOURN/ai-nnflex/AI-NNFlex-0.1.tar.gz
C/CC/CCOLBOURN/ai-nnflex/AI-NNFlex-0.20.tar.gz
C/CC/CCOLBOURN/ai-nnflex/AI-NNFlex-0.21.tar.gz
C/CC/CCOLBOURN/ai-nnflex/ai-nnflex-0.1.tar.gz
C/CH/CHAMAS/Apache-ASP-0.02.tar.gz
C/CH/CHAMAS/Apache-ASP-0.03.tar.gz
C/CH/CHARTGRP/Chart-2.2.tar.gz
C/CH/CHLIGE/TAM-Admin-0.25.tar.gz
C/CH/CHLIGE/TAM-Admin-0.3.tar.gz
C/CH/CHLIGE/TAM-Admin-0.35.tar.gz
C/CH/CHRWOLF/Msgcat-1.00.tar.gz
C/CH/CHRWOLF/Msgcat-1.01.tar.gz
C/CK/CKAISER/httpi-0.4.tar.gz
C/CK/CKAISER/httpi-0.99.tar.gz
C/CK/CKAISER/httpi-1.2.1.tar.gz
C/CK/CKAISER/httpi-1.3.1.tar.gz
C/CK/CKAISER/httpi-1.3.2.tar.gz
C/CK/CKAISER/httpi-1.3.tar.gz
C/CK/CKAISER/httpi-1.4.tar.gz
C/CK/CKAISER/httpi-1.5.1.tar.gz
C/CK/CKAISER/httpi-1.5.tar.gz
C/CK/CKAISER/httpi-1.6.1.tar.gz
C/CK/CKAISER/httpi-1.6.tar.gz
C/CK/CKAISER/httpi-1.7.tar.gz
C/CT/CTWETEN/Tie-SortHash-1.00.tar.gz
C/CT/CTWETEN/Tie-SortHash-1.01.tar.gz
C/CT/CTWETEN/override-1.01.tar.gz
C/CW/CWHITE/HPUX-FS_0.01.tar.gz
C/CW/CWHITE/HPUX-FS_0.02.tar.gz
C/CY/CYK/Isam-0.2.tar.gz
D/DA/DAVECROSS/Array-Compare-1.03.tar.gz
D/DA/DAVECROSS/Tie-Hash-Regex-0.01.tar.gz
D/DA/DAVIDH/Sub-Curry-0.07.tar.gz
D/DA/DAVIDH/Sub-Curry-0.08.tar.gz
D/DD/DDUMONT/Async-Group-0.2.tar.gz
D/DD/DDUMONT/Async-Group-0.3.tar.gz
D/DD/DDUMONT/Puppet-Any-0.01.tar.gz
D/DD/DDUMONT/Puppet-Any-0.04.tar.gz
D/DD/DDUMONT/Puppet-Body-1.012.tar.gz
D/DD/DDUMONT/Puppet-Body-1.018.tar.gz
D/DD/DDUMONT/Puppet-Log-1.010.tar.gz
D/DD/DDUMONT/Puppet-Log-1.011.tar.gz
D/DD/DDUMONT/Puppet-Show-1.002.tar.gz
D/DD/DDUMONT/Puppet-Show-1.003.tar.gz
D/DD/DDUMONT/Puppet-Show-1.005.tar.gz
D/DD/DDUMONT/Puppet-Show-1.007.tar.gz
D/DD/DDUMONT/Puppet-VcsTools-File-1.002.tar.gz
D/DD/DDUMONT/Puppet-VcsTools-File-1.003.tar.gz
D/DD/DDUMONT/Puppet-VcsTools-History-1.001.tar.gz
D/DD/DDUMONT/Puppet-VcsTools-History-1.002.tar.gz
D/DD/DDUMONT/Puppet-VcsTools-History-1.003.tar.gz
D/DD/DDUMONT/Puppet-VcsTools-History-1.004.tar.gz
D/DD/DDUMONT/RPC-Simple-0.2.tar.gz
D/DD/DDUMONT/RPC-Simple-0.3.tar.gz
D/DD/DDUMONT/Text-Vpp-0.02.tar.gz
D/DD/DDUMONT/Text-Vpp-0.03.tar.gz
D/DD/DDUMONT/Text-Vpp-0.04.tar.gz
D/DD/DDUMONT/Text-Vpp-0.1.tar.gz
D/DD/DDUMONT/Text-Vpp-0.2.tar.gz
D/DD/DDUMONT/Text-Vpp-1.01.tar.gz
D/DD/DDUMONT/Text-Vpp-1.1.tar.gz
D/DD/DDUMONT/Text-Vpp-1.11.tar.gz
D/DD/DDUMONT/Tk-Multi-0.01.tar.gz
D/DD/DDUMONT/Tk-Multi-0.02.tar.gz
D/DD/DDUMONT/Tk-Multi-0.03.tar.gz
D/DD/DDUMONT/Tk-Multi-0.1.tar.gz
D/DD/DDUMONT/Tk-Multi-0.2.tar.gz
D/DD/DDUMONT/Tk-Multi-0.3.tar.gz
D/DD/DDUMONT/Tk-Multi-0.4.tar.gz
D/DD/DDUMONT/Tk-Multi-0.6.tar.gz
D/DD/DDUMONT/Tk-Multi-0.72.tar.gz
D/DD/DDUMONT/Tk-Multi-0.73.tar.gz
D/DD/DDUMONT/Tk-Multi-0.80.tar.gz
D/DD/DDUMONT/Tk-Multi-1.001.tar.gz
D/DD/DDUMONT/Tk-Multi-1.002.tar.gz
D/DD/DDUMONT/Tk-Multi-1.003.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-0.01.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-0.02.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-0.1.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-0.2.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-0.3.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-0.4.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-0.5.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-1.011.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-1.013.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-1.014.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-1.016.tar.gz
D/DD/DDUMONT/Tk-ObjScanner-1.017.tar.gz
D/DD/DDUMONT/Tk-TreeGraph-1.004.tar.gz
D/DD/DDUMONT/Tk-TreeGraph-1.005.tar.gz
D/DD/DDUMONT/VcsTools-0.01.tar.gz
D/DD/DDUMONT/VcsTools-File-1.001.tar.gz
D/DD/DDUMONT/VcsTools-File-1.002.tar.gz
D/DD/DDUMONT/VcsTools-File-1.003.tar.gz
D/DD/DDUMONT/VcsTools-File-1.004.tar.gz
D/DD/DDUMONT/VcsTools-History-1.001.tar.gz
D/DD/DDUMONT/VcsTools-History-1.002.tar.gz
D/DD/DDUMONT/VcsTools-History-1.003.tar.gz
D/DD/DDUMONT/VcsTools-History-1.004.tar.gz
D/DF/DFRENCH/AIX-ODM-1.0.1.tar.gz
D/DF/DFRENCH/AIX-ODM-1.0.2.tar.gz
D/DF/DFRENCH/AIX-ODM-1.0.tar.gz
D/DO/DOMIZIO/HTML-TableTiler-1.0.tar.gz
D/DO/DOMIZIO/HTML-TableTiler-1.01.tar.gz
D/DO/DOMIZIO/Text-MagicTemplate-1.0.tar.gz
D/DO/DOMIZIO/Text-MagicTemplate-1.1.tar.gz
D/DO/DOMIZIO/Text-MagicTemplate-1.2.tar.gz
D/DO/DOMIZIO/Text-MagicTemplate-1.21.tar.gz
D/DO/DOMIZIO/Text-MagicTemplate-1.22.tar.gz
D/DO/DOMIZIO/Text-MagicTemplate-1.23.tar.gz
D/DO/DOMIZIO/Text-MagicTemplate-1.31.tar.gz
D/DO/DOMIZIO/Text-MagicTemplate-2.0.tar.gz
D/DO/DOMIZIO/Text-MagicTemplate-2.01.tar.gz
D/DO/DOMIZIO/Text-MagicTemplate-2.02.tar.gz
D/DO/DOMIZIO/Text-MagicTemplate-2.03.tar.gz
D/DO/DOMIZIO/Text-MagicTemplateX-HTML-1.0.tar.gz
D/DO/DOMIZIO/Text-MagicTemplateX-HTML-1.01.tar.gz
D/DO/DOMIZIO/Text-MagicTemplateX-HTML-1.02.tar.gz
D/DO/DOUGM/Apache-Perl-contrib-042797.tar.gz
D/DO/DOUGM/Apache-Perl-contrib-061197.tar.gz
D/DO/DOUGM/Apache-Perl-contrib-062997.tar.gz
D/DO/DOUGM/DCE-Perl-0.11.tar.gz
D/DO/DOUGM/DCE-Perl-0.15.tar.gz
D/DO/DOUGM/ExtUtils-Embed-1.12_02.tar.gz
D/DO/DOUGM/ExtUtils-Embed-1.12_03.tar.gz
D/DO/DOUGM/HTTPD-Tools-0.52.tar.gz
D/DO/DOUGM/HTTPD-Tools-0.53.tar.gz
D/DO/DOUGM/HTTPD-Tools-0.54.tar.gz
D/DO/DOUGM/HTTPD-Tools-0.55.tar.gz
D/DO/DOUGM/mod_perl-0.60a2.tar.gz
D/DO/DOUGM/mod_perl-0.60a5.tar.gz
D/DO/DOUGM/mod_perl-0.70b1.tar.gz
D/DO/DOUGM/mod_perl-0.76b1.tar.gz
D/DO/DOUGM/mod_perl-0.81.tar.gz
D/DO/DOUGM/mod_perl-0.83_02.tar.gz
D/DO/DOUGM/mod_perl-0.83_03.tar.gz
D/DO/DOUGM/mod_perl-0.83_04.tar.gz
D/DO/DOUGM/mod_perl-0.83_06.tar.gz
D/DO/DOUGM/mod_perl-0.83_07.tar.gz
D/DO/DOUGM/mod_perl-0.83_09.tar.gz
D/DO/DOUGM/mod_perl-0.83_10.tar.gz
D/DO/DOUGM/mod_perl-0.84.tar.gz
D/DO/DOUGM/mod_perl-0.85.tar.gz
D/DO/DOUGM/mod_perl-0.85_04.tar.gz
D/DO/DOUGM/mod_perl-0.86.tar.gz
D/DO/DOUGM/mod_perl-0.87.tar.gz
D/DO/DOUGM/mod_perl-0.88.tar.gz
D/DO/DOUGM/mod_perl-0.89.tar.gz
D/DO/DOUGM/mod_perl-0.90_01.tar.gz
D/DO/DOUGM/mod_perl-0.91.tar.gz
D/DO/DOUGM/mod_perl-0.92.tar.gz
D/DO/DOUGM/mod_perl-0.93_01.tar.gz
D/DO/DOUGM/mod_perl-0.94.tar.gz
D/DO/DOUGM/mod_perl-0.95_02.tar.gz
D/DO/DOUGM/mod_perl-0.95_03.tar.gz
D/DO/DOUGM/mod_perl-0.95_04.tar.gz
D/DO/DOUGM/mod_perl-0.95_05.tar.gz
D/DO/DOUGM/mod_perl-0.95_06.tar.gz
D/DO/DOUGM/mod_perl-0.96.tar.gz
D/DO/DOUGM/mod_perl-0.97.tar.gz
D/DO/DOUGM/mod_perl-0.98_03.tar.gz
D/DO/DOUGM/mod_perl-0.98_09.tar.gz
D/DO/DOUGM/mod_perl-0.98_10.tar.gz
D/DO/DOUGM/mod_perl-0.98_11.tar.gz
D/DO/DOUGM/mod_perl-0.99.tar.gz
D/DO/DOUGM/mod_perl-1.00b1.tar.gz
D/DO/DOUGM/mod_perl-1.00b2.tar.gz
D/DO/DOUGW/Convert-TNEF-0.05.tar.gz
D/DO/DOUGW/Convert-TNEF-0.06.tar.gz
D/DO/DOUGW/Convert-TNEF-0.07.tar.gz
D/DO/DOUGW/Convert-TNEF-0.08.tar.gz
D/DO/DOUGW/Parse-FixedLength-5.31.tar.gz
D/DR/DROBERTS/File-Repl-0.4.tar.gz
D/DR/DROBERTS/File-Repl0.4.tar.gz
E/EI/EIJABB/MARC-Errorchecks-1.04.tar.gz
E/EI/EIJABB/MARC-Errorchecks-1.05.tar.gz
E/EI/EIJABB/MARC-Errorchecks-1.06.tar.gz
E/EI/EIJABB/MARC-Errorchecks-1.08.tar.gz
E/EI/EIJABB/MARC-Errorchecks-1.09.tar.gz
E/EI/EIJABB/MARC-Errorchecks-1.13.tar.gz
E/EI/EIJABB/MARC-Errorchecks-1.14.tar.gz
E/EI/EIJABB/MARC-Lint-1.41.tar.gz
E/EI/EIJABB/MARC-Lint-1.42.tar.gz
E/EI/EIJABB/MARC-Lint-1.43.tar.gz
E/EI/EIJABB/MARC-Lint-1.44.tar.gz
E/EI/EIJABB/marc-lint-1.41.tar.gz
F/FM/FMC/Sx-2.2.tar.gz
F/FP/FPIVARI/GraphMaker-1.1.tar.gz
F/FP/FPIVARI/GraphMaker-2.0.tar.gz
F/FP/FPIVARI/GraphMaker-2.1.tar.gz
F/FP/FPIVARI/pgphtml-1.0.tar.gz
F/FP/FPIVARI/unpgphtml-1.0.tar.gz
F/FS/FSORIANO/Tree-Nary-1.3.tar.gz
G/GB/GBARR/FindBin-1.01.tar.gz
G/GB/GBARR/MailTools-1.04.tar.gz
G/GE/GENJISCH/Convert-Translit-1.00.tar.gz
G/GE/GENJISCH/Convert-Translit-1.01.tar.gz
G/GE/GENJISCH/Convert-Translit-1.02.tar.gz
G/GG/GGONTER/hp200lx-0.1.tar.gz
G/GG/GGONTER/hp200lx-0.2.tar.gz
G/GL/GLOVER/Cdk-ext-4.7.0.tar.gz
G/GM/GMLEWIS/RenderMan-0.02.tar.gz
G/GR/GROMMEL/Acme-Turing-0.01.tar.gz
G/GR/GROMMEL/Convert-IBM390-0.01.tar.gz
G/GR/GROMMEL/Convert-IBM390-0.15.tar.gz
G/GR/GROMMEL/Convert-IBM390-0.15X.tar.gz
G/GR/GROMMEL/Convert-IBM390-0.18.tar.gz
G/GR/GROMMEL/Convert-IBM390-0.19.tar.gz
G/GR/GROMMEL/Convert-IBM390-0.25.tar.gz
G/GR/GROMMEL/Convert-IBM390p-0.01.tar.gz
G/GR/GROMMEL/MVS-VBFile-0.01.tar.gz
G/GR/GROMMEL/MVS-VBFile-0.03.tar.gz
G/GR/GROMMEL/MVS-VBFile-0.05.tar.gz
G/GR/GROMMEL/Math-Random-0.62.tar.gz
G/GR/GROMMEL/Math-Random-0.64.tar.gz
G/GR/GROMMEL/Math-Random-0.65.tar.gz
G/GR/GROMMEL/Math-Random-0.66.tar.gz
G/GR/GROMMEL/Math-Round-0.01.tar.gz
G/GR/GROMMEL/Math-Round-0.03.tar.gz
G/GR/GROMMEL/Math-Round-0.04.tar.gz
G/GR/GROMMEL/Math-Round-0.05.tar.gz
G/GR/GROMMEL/Teradata-SQL-0.04.tar.gz
G/GR/GROMMEL/Teradata-SQL-0.05.tar.gz
G/GR/GROMMEL/Teradata-SQL-0.06.tar.gz
G/GS/GSAR/Data-Dumper-1.22.tar.gz
H/HA/HAWKINSM/IBM-LoadLeveler-0.07.tar.gz
H/HA/HAWKINSM/IBM-LoadLeveler-1.03.tar.gz
H/HA/HAWKINSM/IBM-LoadLeveler-1.04.tar.gz
H/HA/HAWKINSM/LoadLeveler-0.05.tar.gz
H/HM/HMBRAND/DBD-Unify-0.10.tar.gz
H/HM/HMBRAND/DBD-Unify-0.11.tgz
H/HM/HMBRAND/DBD-Unify-0.23.tgz
H/HM/HMBRAND/DBD-Unify-0.24.tgz
H/HM/HMBRAND/DBD-Unify-0.25.tgz
H/HM/HMBRAND/DBD-Unify-0.42.tgz
H/HM/HMBRAND/DBD-Unify-0.60.tgz
H/HM/HMBRAND/DBD-Unify-0.61.tgz
H/HM/HMBRAND/Test-Smoke-1.08.tgz
H/HM/HMBRAND/Test-Smoke-1.11.tgz
H/HM/HMBRAND/Text-OutputFilter-0.11.tgz
H/HM/HMBRAND/Tk-Clock-0.05.tar.gz
H/HM/HMBRAND/Tk-Clock-0.10.tgz
H/HM/HMBRAND/Tk-Clock-0.11.tgz
H/HP/HPALM/VRML-0.90.tar.gz
H/HP/HPALM/VRML-0.91.tar.gz
H/HP/HPALM/VRML-0.92.tar.gz
H/HP/HPALM/VRML-0.97.tar.gz
H/HT/HTOUG/DBD-Ingres-0.04.tar.gz
H/HT/HTOUG/DBD-Ingres-0.05.tar.gz
H/HT/HTOUG/DBD-Ingres-0.0504.tar.gz
H/HT/HTOUG/DBD-Ingres-0.05_91.tar.gz
H/HT/HTOUG/DBD-Ingres-0.05_92.tar.gz
H/HT/HTOUG/DBD-Ingres-0.05_93.tar.gz
H/HT/HTOUG/DBD-Ingres-0.05_96.tar.gz
H/HT/HTOUG/DBD-Ingres-0.10.tar.gz
H/HT/HTOUG/DBD-Ingres-0.11.tar.gz
H/HT/HTOUG/DBD-Ingres-0.13.tar.gz
H/HT/HTOUG/DBD-Ingres-0.14.tar.gz
H/HT/HTOUG/DBD-Ingres-0.16.tar.gz
H/HT/HTOUG/DBD-Ingres-0.19_1.tar.gz
H/HT/HTOUG/DBD-Ingres-0.19_3.tar.gz
H/HT/HTOUG/DBD-Ingres-0.20.tar.gz
H/HT/HTOUG/DBD-Ingres-0.21.tar.gz
H/HT/HTOUG/DBD-Ingres-0.22.tar.gz
H/HT/HTOUG/DBD-Ingres-0.24.tar.gz
H/HT/HTOUG/DBD-Ingres-0.25.tar.gz
H/HT/HTOUG/DBD-Ingres-0.26.tar.gz
H/HT/HTOUG/DBD-Ingres-0.27.tar.gz
H/HT/HTOUG/DBD-Ingres-0.28.tar.gz
H/HT/HTOUG/DBD-Ingres-0.29.tar.gz
H/HT/HTOUG/DBD-Ingres-0.30.tar.gz
H/HT/HTOUG/DBD-Ingres-0.31.tar.gz
H/HT/HTOUG/DBD-Ingres-0.32.tar.gz
H/HT/HTOUG/DBD-Ingres-0.36.tar.gz
H/HT/HTOUG/DBD-Ingres-0.37.tar.gz
H/HT/HTOUG/DBD-Ingres-0.38.tar.gz
H/HT/HTOUG/DBD-Ingres-0.39.tar.gz
H/HT/HTOUG/DBD-Ingres-0.51.tar.gz
I/IB/IBMTORDB2/DBD-DB2-0.73.tar.gz
I/IB/IBMTORDB2/DBD-DB2-0.76.tar.gz
I/IB/IBMTORDB2/DBD-DB2-0.77.tar.gz
I/IB/IBMTORDB2/DBD-DB2.0.77.tar.gz
I/IG/IGUTHRIE/Filesys-Statvfs-0.43.tar.gz
I/IG/IGUTHRIE/Filesys-Statvfs_Df-0.44.tar.gz
I/IG/IGUTHRIE/Filesys-Statvfs_Df-0.45.tar.gz
I/IG/IGUTHRIE/Filesys-Statvfs_Df-0.47.tar.gz
I/IG/IGUTHRIE/Filesys-Statvfs_Df-0.49.tar.gz
I/IG/IGUTHRIE/Filesys-Statvfs_Df-0.50.tar.gz
I/IG/IGUTHRIE/Filesys-Statvfs_Df-0.52.tar.gz
I/IG/IGUTHRIE/Filesys-Statvfs_Df-0.57.tar.gz
I/IG/IGUTHRIE/Filesys-Statvfs_Df-0.61.tar.gz
I/IG/IGUTHRIE/Filesys-Statvfs_Df-0.65.tar.gz
I/IL/ILTZU/Tie-CharArray-0.02.tar.gz
I/IL/ILTZU/Tie-CharArray-1.00.tar.gz
J/JA/JACKS/IPC_SysV.tar.gz
J/JA/JACKS/InitializeServer-1.0.tar.gz
J/JA/JACKS/Prolog-alpha.tar.gz
J/JA/JACKS/UNIVERSAL-1.0.tar.gz
J/JA/JARIAALTO/Lingua-EN-Squeeze-1998.1204.tar.gz
J/JB/JBUHACOFF/CGI-Session-BitBucket-1.1.tar.gz
J/JB/JBUHACOFF/CGI-Session-BitBucket-1.2.tar.gz
J/JB/JBUHACOFF/CGI-Session-Driver-bitbucket-1.06.tar.gz
J/JB/JBUHACOFF/Data-SimplePaginator-0.3.tar.gz
J/JB/JBUHACOFF/Data-SimplePaginator-0.5.tar.gz
J/JE/JEDWARDS/PDL-IO-Grib-2.0.tar.gz
J/JE/JEFFH/Apache-AuthenPasswdSrv-0.01.tar.gz
J/JH/JHI/Acme-Ook-0.04.tar.gz
J/JH/JHI/Acme-Ook-0.05.tar.gz
J/JH/JHI/Acme-Ook-0.06.tar.gz
J/JH/JHI/Acme-Ook-0.07.tar.gz
J/JH/JHI/Acme-Ook-0.08.tar.gz
J/JH/JHI/Acme-Ook-0.09.tar.gz
J/JH/JHI/BSD-Resource-1.03.tar.gz
J/JH/JHI/BSD-Resource-1.05.tar.gz
J/JH/JHI/BSD-Resource-1.05_01.tar.gz
J/JH/JHI/BSD-Resource-1.05_02.tar.gz
J/JH/JHI/BSD-Resource-1.06.tar.gz
J/JH/JHI/BSD-Resource-1.07.00.tar.gz
J/JH/JHI/BSD-Resource-1.0701.tar.gz
J/JH/JHI/BSD-Resource-1.09.tar.gz
J/JH/JHI/BSD-Resource-1.10.tar.gz
J/JH/JHI/BSD-Resource-1.11.tar.gz
J/JH/JHI/BSD-Resource-1.15.tar.gz
J/JH/JHI/BSD-Resource-1.17.tar.gz
J/JH/JHI/BSD-Resource-1.18.tar.gz
J/JH/JHI/BSD-Resource-1.19.tar.gz
J/JH/JHI/BSD-Resource-1.21.tar.gz
J/JH/JHI/BSD-Resource-1.22.tar.gz
J/JH/JHI/BSD-Resource-1.23.tar.gz
J/JH/JHI/BSD-Time-0.01.tar.gz
J/JH/JHI/BSD-Time-0.02.tar.gz
J/JH/JHI/BSD-Time-0.03.tar.gz
J/JH/JHI/Class-Privacy-0.03.tar.gz
J/JH/JHI/Graph-0.20102.tar.gz
J/JH/JHI/Lingua-FI-Hyphenate-0.02.tar.gz
J/JH/JHI/Lingua-FI-Hyphenate-0.03.tar.gz
J/JH/JHI/Lingua-FI-Hyphenate-0.04.tar.gz
J/JH/JHI/Lingua-FI-Kontti-0.01.tar.gz
J/JH/JHI/Lingua-FI-Kontti-0.02.tar.gz
J/JH/JHI/Lingua-FI-Transcribe-0.02.tar.gz
J/JH/JHI/Lingua-FI-Transcribe-0.03.tar.gz
J/JH/JHI/Regex-PreSuf-0.002.tar.gz
J/JH/JHI/Regex-PreSuf-0.003.tar.gz
J/JH/JHI/Regex-PreSuf-0.004.tar.gz
J/JH/JHI/Regex-PreSuf-0.005.tar.gz
J/JH/JHI/Regex-PreSuf-1.01.tar.gz
J/JH/JHI/Regex-PreSuf-1.10.tar.gz
J/JH/JHI/Regex-PreSuf-1.11.tar.gz
J/JH/JHI/Regex-PreSuf-1.12.tar.gz
J/JH/JHI/Set-Bag-1.001.tar.gz
J/JH/JHI/Set-Bag-1.002.tar.gz
J/JH/JHI/Set-Bag-1.004.tar.gz
J/JH/JHI/Set-Bag-1.006.tar.gz
J/JH/JHI/Set-Bag-1.007.tar.gz
J/JH/JHI/Set-Bag-1.008.tar.gz
J/JH/JHI/Set-Scalar-0.004.tar.gz
J/JH/JHI/Set-Scalar-0.00401.tar.gz
J/JH/JHI/Set-Scalar-1.01.tar.gz
J/JH/JHI/Set-Scalar-1.02.tar.gz
J/JH/JHI/Set-Scalar-1.03.tar.gz
J/JH/JHI/Set-Scalar-1.04.tar.gz
J/JH/JHI/Set-Scalar-1.05.tar.gz
J/JH/JHI/Set-Scalar-1.06.tar.gz
J/JH/JHI/Set-Scalar-1.07.tar.gz
J/JH/JHI/Set-Scalar-1.08.tar.gz
J/JH/JHI/Set-Scalar-1.09.tar.gz
J/JH/JHI/Set-Scalar-1.10.tar.gz
J/JH/JHI/Set-Scalar-1.11.tar.gz
J/JH/JHI/Set-Scalar-1.12.tar.gz
J/JH/JHI/Set-Scalar-1.16.tar.gz
J/JH/JHI/Set-Scalar-1.17.tar.gz
J/JH/JHI/Set-Scalar-1.18.tar.gz
J/JH/JHI/Set-Scalar-1.19.tar.gz
J/JH/JHI/Statistics-DEA-0.01.tar.gz
J/JH/JHI/Statistics-Frequency-0.01.tar.gz
J/JH/JHI/Statistics-Shannon-0.01.tar.gz
J/JH/JHI/Statistics-Shannon-0.02.tar.gz
J/JH/JHI/Statistics-Shannon-0.03.tar.gz
J/JH/JHI/Statistics-Simpson-0.01.tar.gz
J/JH/JHI/String-Approx-2.0.tar.gz
J/JH/JHI/String-Approx-2.0_01.tar.gz
J/JH/JHI/String-Approx-2.2.tar.gz
J/JH/JHI/String-Approx-2.3.tar.gz
J/JH/JHI/String-Approx-2.4.tar.gz
J/JH/JHI/String-Approx-2.5.tar.gz
J/JH/JHI/String-Approx-2.6.tar.gz
J/JH/JHI/String-Approx-2.7.tar.gz
J/JH/JHI/String-Approx-3.01.tar.gz
J/JH/JHI/String-Approx-3.02.tar.gz
J/JH/JHI/String-Approx-3.03.tar.gz
J/JH/JHI/String-Approx-3.04.tar.gz
J/JH/JHI/String-Approx-3.08.tar.gz
J/JH/JHI/String-Approx-3.09.tar.gz
J/JH/JHI/String-Approx-3.10.tar.gz
J/JH/JHI/String-Approx-3.11.tar.gz
J/JH/JHI/String-Approx-3.15.tar.gz
J/JH/JHI/String-Approx-3.16.tar.gz
J/JH/JHI/String-Approx-3.17.tar.gz
J/JH/JHI/String-Approx-3.18.tar.gz
J/JH/JHI/String-Approx-3.19.tar.gz
J/JH/JHI/String-Approx-3.20.tar.gz
J/JH/JHI/String-Approx-3.22.tar.gz
J/JH/JHI/String-Scanf-2.0.tar.gz
J/JH/JHI/Time-HiRes-1.31.tar.gz
J/JH/JHI/Time-HiRes-1.34.tar.gz
J/JH/JHI/Time-HiRes-1.56.tar.gz
J/JH/JHOWELL/FAQ-OMatic-2.501.tar.gz
J/JH/JHOWELL/FAQ-OMatic-2.602.tar.gz
J/JH/JHOWELL/FAQ-OMatic-2.606.tar.gz
J/JH/JHOWELL/FAQ-OMatic-2.609.tar.gz
J/JH/JHOWELL/FAQ-OMatic-2.610.tar.gz
J/JH/JHOWELL/FAQ-OMatic-2.611.tar.gz
J/JH/JHOWELL/FAQ-OMatic-2.615.tar.gz
J/JI/JIANGS/CaCORE-3.01.tar.gz
J/JI/JIANGS/CaCORE-3.092.tar.gz
J/JM/JMM/Heap-0.50.tar.gz
J/JO/JONG/bio_lib.1.7.tar.gz
J/JO/JONG/evalign.1.5.tar.gz
J/JO/JONG/geanfammer.1.3.tar.gz
J/JO/JONG/sc_rate_1.1.tar.gz
J/JO/JONO/Statistics-ChiSquare-0.2.tar.gz
J/JP/JPEACOCK/Math-Currency-0.08.tar.gz
J/JP/JPEACOCK/Math-Currency-0.09.tar.gz
J/JP/JPEACOCK/Math-FixedPrecision-0.02.tar.gz
J/JP/JPEACOCK/Math-FixedPrecision-0.03.tar.gz
J/JP/JPEACOCK/Math-FixedPrecision-0.04.tar.gz
J/JP/JPEACOCK/Math-FixedPrecision-0.05.tar.gz
J/JP/JPEACOCK/Math-FixedPrecision-0.06.tar.gz
J/JP/JPEACOCK/Math-FixedPrecision-0.11.tar.gz
J/JP/JPRAVETZ/pod2ps-1.0.1.tar.gz
K/KA/KARLON/Chart-Pie-0.90.tar.gz
K/KG/KGB/ExtUtils-F77-1.01.tar.gz
K/KG/KGB/PGPLOT-2.0.tar.gz
K/KG/KGB/PGPLOT-2.01.tar.gz
K/KG/KGB/PGPLOT-2.02.tar.gz
K/KG/KGB/PGPLOT-2.04.tar.gz
K/KG/KGB/PGPLOT-2.06.tar.gz
K/KG/KGB/PGPLOT1.0b_src.tar.gz
K/KW/KWILLIAMS/Apache-Filter-0.01.tar.gz
K/KW/KWILLIAMS/Apache-Filter-0.05.tar.gz
K/KW/KWILLIAMS/Apache-Filter-0.06.tar.gz
K/KW/KWILLIAMS/Apache-Filter-0.07.tar.gz
K/KW/KWILLIAMS/Apache-Filter-0.08.tar.gz
K/KW/KWILLIAMS/Apache-Filter-0.09.tar.gz
K/KW/KWILLIAMS/Apache-Filter-0.10.tar.gz
K/KW/KWILLIAMS/Apache-SSI-1.90.tar.gz
K/KW/KWILLIAMS/Apache-SSI-1.91.tar.gz
K/KW/KWILLIAMS/Apache-SSI-1.92.tar.gz
K/KW/KWILLIAMS/Apache-SSI-1.94.tar.gz
K/KW/KWILLIAMS/Apache-SSI-2.02.tar.gz
K/KW/KWILLIAMS/Apache-SSI-2.04.tar.gz
K/KW/KWILLIAMS/Apache-SSI-2.05.tar.gz
K/KW/KWILLIAMS/File-Backup-0.01.tar.gz
K/KW/KWILLIAMS/File-Backup-0.02.tar.gz
K/KW/KWILLIAMS/HTML-SimpleParse-0.01.tar.gz
K/KW/KWILLIAMS/HTML-SimpleParse-0.02.tar.gz
K/KW/KWILLIAMS/HTML-SimpleParse-0.05.tar.gz
K/KW/KWILLIAMS/HTML-SimpleParse-0.06.tar.gz
K/KW/KWILLIAMS/Math-BaseCalc-1.007.tar.gz
K/KW/KWILLIAMS/Taco-0.01.tar.gz
K/KW/KWILLIAMS/Taco-0.02.tar.gz
K/KW/KWILLIAMS/Taco-0.03.tar.gz
K/KW/KWILLIAMS/Text-FillIn-0.01.tar.gz
K/KW/KWILLIAMS/Text-FillIn-0.02.tar.gz
K/KW/KWILLIAMS/Text-FillIn-0.03.tar.gz
K/KW/KWILLIAMS/Text-FillIn-0.05.tar.gz
K/KW/KWILLIAMS/Tie-DB_Lock-0.01.tar.gz
K/KW/KWILLIAMS/Tie-DB_Lock-0.02.tar.gz
K/KW/KWILLIAMS/Tie-DB_Lock-0.03.tar.gz
K/KW/KWILLIAMS/Tie-DB_Lock-0.04.tar.gz
K/KW/KWILLIAMS/Tie-DB_Lock-0.05.tar.gz
K/KW/KWILLIAMS/Tie-LLHash-0.01.tar.gz
K/KW/KWILLIAMS/Tie-LLHash-0.02.tar.gz
K/KW/KWILLIAMS/Tie-LLHash-0.03.tar.gz
K/KW/KWILLIAMS/Tie-TextDir-0.01.tar.gz
K/KW/KWILLIAMS/Tie-TextDir-0.02.tar.gz
K/KW/KWILLIAMS/Tie-TextDir-0.03.tar.gz
L/LB/LBENDAVID/Net-Telnet-Brcd-0.19.tar.gz
L/LB/LBENDAVID/Net-Telnet-Brcd-1.12.tar.gz
L/LI/LINDNER/HTML-Clean-0.7.tar.gz
L/LU/LUISMUNOZ/NetAddr-IP-2.24.tar.gz
L/LU/LUSOL/Getopt-EvaP-2.3.1.tar.gz
L/LU/LUSOL/Getopt-EvaP-2.3.2.tar.gz
L/LU/LUSOL/Tie-Watch-0.92.tar.gz
L/LU/LUSOL/Tie-Watch-0.94.tar.gz
L/LU/LUSOL/Tie-Watch-0.95.tar.gz
L/LU/LUSOL/Tie-Watch-0.97.tar.gz
M/ME/MEWP/DBD-Sybase-0.01.tar.gz
M/MH/MHM/DBD-DB2-0.63.tar.gz
M/MH/MHM/DBD-DB2-0.64.tar.gz
M/MH/MHM/DBD-DB2-0.69.tar.gz
M/MH/MHM/DBD-DB2-0.70.tar.gz
M/MI/MIKEDLR/Tie-TransactHash-0.01.tar.gz
M/MP/MPIOTR/Lingua-Ident-1.0.tar.gz
M/MP/MPIOTR/Locale-Iconv-0.01.tar.gz
M/MP/MPIOTR/Text-Iconv-1.0.tar.gz
M/MP/MPIOTR/Text-Iconv-1.1.tar.gz
M/MP/MPIOTR/Text-Iconv-1.2.tar.gz
M/MP/MPIOTR/User-Utmp-0.02.tar.gz
M/MP/MPIOTR/User-Utmp-1.0.tar.gz
M/MP/MPIOTR/User-Utmp-1.01.tar.gz
M/MP/MPIOTR/User-Utmp-1.6.tar.gz
M/MS/MSICKEL/geo-ecef-1.0.0.tar.gz
M/MU/MUENALAN/Class-Maker-0.01.tar.gz
N/NI/NI-S/Ptty-0.01.tar.gz
N/NI/NI-S/Tk-JPEG-b11.tar.gz
N/NI/NI-S/Tk-b8.tar.gz
N/NI/NI-S/Tk-b9.01.tar.gz
N/NI/NI-S/Tk-b9.tar.gz
N/NO/NOG/rcsfreeze-1.7.tar.gz
N/NO/NOG/rcsfreeze-1.8.tar.gz
N/NW/NWINT/MD5-1.2.1.tar.gz
N/NW/NWINT/MD5-1.5.3.tar.gz
N/NW/NWINT/MD5-1.6.tar.gz
N/NW/NWINT/MD5-1.7.tar.gz
N/NW/NWRIGHT/GIFgraph-Boxplot-1.00.tar.gz
O/OE/OESTERHOL/Term-Screen-ReadLine-0.33.tar.gz
O/OE/OESTERHOL/Term-Screen-Wizard-0.20.tar.gz
O/OE/OESTERHOL/Term-Screen-Wizard-0.45.tar.gz
O/OE/OESTERHOL/Term-Screen-Wizard-0.46.tar.gz
O/OE/OESTERHOL/Term-Screen-Wizard-0.47.tar.gz
O/OE/OESTERHOL/Term-Screen-Wizard-0.48.tar.gz
O/OK/OKAMOTO/MIME-Types-0.01.tar.gz
O/OK/OKAMOTO/MIME-Types-0.02.tar.gz
O/OK/OKAMOTO/MIME-Types-0.03.tar.gz
P/PA/PAULG/Logfile-Rotate-0.07.tar.gz
P/PA/PAULG/Logfile-Rotate-0.12.tar.gz
P/PA/PAULG/Logfile-Rotate-1.03.tar.gz
P/PA/PAYERLE/Net-Hesiod-1.10a.tar.gz
P/PA/PAYERLE/Net-Hesiod-1.11.tar.gz
P/PF/PFRANCEUS/LSF-Base-0.01.tar.gz
P/PF/PFRANCEUS/LSF-Batch-0.01.tar.gz
P/PM/PMQS/BerkDB-0.01.tar.gz
P/PM/PMQS/BerkeleyDB-0.02.tar.gz
P/PM/PMQS/Compress-Zlib-1.00.tar.gz
P/PM/PMQS/Compress-Zlib-1.01.tar.gz
P/PM/PMQS/DB_File-1.14.tar.gz
P/PM/PMQS/DB_File-1.15.tar.gz
P/PM/PMQS/DB_File-1.16.tar.gz
P/PM/PMQS/DB_File-1.51Beta.tar.gz
P/PM/PMQS/DB_File-1.57.tar.gz
P/PM/PMQS/DB_File-1.58.tar.gz
P/PM/PMQS/Filter-1.09.tar.gz
P/PM/PMQS/Filter-1.10.tar.gz
P/PM/PMQS/Filter-1.12.tar.gz
P/PM/PMQS/Filter-1.13.tar.gz
P/PM/PMQS/xsubpp-1.922.tar.gz
P/PR/PRL/PCL-Simple-1.tar.gz
P/PR/PRL/Term-Interact-0.40.tar.gz
P/PR/PRL/Term-Interact-0.41.tar.gz
P/PR/PRL/Term-Interact-0.42.tar.gz
P/PR/PRL/Term-Interact-0.43.tar.gz
P/PR/PRYAN/Period-1.11.tar.gz
P/PV/PVERD/mop-1.06.tar.gz
P/PV/PVHP/OS390-Stdio-0.003.tar.gz
P/PV/PVHP/ptkFAQ-0_03.tar.gz
R/RA/RAM/Storable-0.4@2.tar.gz
R/RA/RAM/Storable-0.4@3.tar.gz
R/RA/RAM/Storable-0.4@4.tar.gz
R/RA/RAM/Storable-0.4@5.tar.gz
R/RA/RAM/Storable-0.4@6.tar.gz
R/RA/RAM/Storable-0.4@7.tar.gz
R/RA/RAM/Storable-0.5@2.tar.gz
R/RA/RAM/Storable-0.5@3.tar.gz
R/RA/RAM/Storable-0.5@5.tar.gz
R/RA/RAM/Storable-0.5@6.tar.gz
R/RA/RAM/Storable-0.6@0.tar.gz
R/RA/RAM/Storable-0.6@1.tar.gz
R/RA/RAM/Storable-0.6@2.tar.gz
R/RA/RAM/cshar-3.0@15.tar.gz
R/RA/RAM/kit-2.0@34.tar.gz
R/RG/RGIERSIG/IO-Tty-0.05.tar.gz
R/RG/RGIERSIG/IO-Tty-1.03.tar.gz
R/RJ/RJRAY/Devel-Coverage-0.1.tar.gz
R/RJ/RJRAY/Image-Size-1.0.tar.gz
R/RJ/RJRAY/Image-Size-1.1.tar.gz
R/RJ/RJRAY/Image-Size-1.2.tar.gz
R/RJ/RJRAY/Image-Size-2.0.tar.gz
R/RJ/RJRAY/Image-Size-2.1.tar.gz
R/RJ/RJRAY/Image-Size-2.2.tar.gz
R/RJ/RJRAY/Image-Size-2.3.tar.gz
R/RJ/RJRAY/Image-Size-2.4.tar.gz
R/RJ/RJRAY/Image-Size-2.5.tar.gz
R/RJ/RJRAY/X11-Fvwm-0.1.tar.gz
R/RJ/RJRAY/X11-Fvwm-0.2.tar.gz
R/RJ/RJRAY/X11-Fvwm-0.4.tar.gz
R/RJ/RJRAY/X11-Fvwm-1.0.tar.gz
R/RK/RKHILL/Astro-Sunrise-0.0201.tar.gz
R/RK/RKHILL/Astro-Sunrise-0.03.tar.gz
S/SA/SAMPO/Net_SSLeay.pm-0.04.tar.gz
S/SB/SBALA/jperl_beta_r1.tar.gz
S/SB/SBURKE/Array-Autojoin-0.01.tar.gz
S/SB/SBURKE/Array-Autojoin-0.02.tar.gz
S/SB/SBURKE/Class-BlackHole-0.02.tar.gz
S/SB/SBURKE/Class-BlackHole-0.03.tar.gz
S/SB/SBURKE/Class-Classless-0.25.tar.gz
S/SB/SBURKE/Class-Classless-1.21.tar.gz
S/SB/SBURKE/Class-Classless-1.22.tar.gz
S/SB/SBURKE/Class-Classless-1.33.tar.gz
S/SB/SBURKE/Class-ISA-0.2.tar.gz
S/SB/SBURKE/Class-ISA-0.32.tar.gz
S/SB/SBURKE/Games-Dissociate-0.12.tar.gz
S/SB/SBURKE/Games-Dissociate-0.13.tar.gz
S/SB/SBURKE/Games-Worms-0.60.tar.gz
S/SB/SBURKE/Games-Worms-Tk-0.41.tar.gz
S/SB/SBURKE/Getopt-constant-1.01.tar.gz
S/SB/SBURKE/Getopt-constant-1.02.tar.gz
S/SB/SBURKE/HTML-Tagset-3.01.tar.gz
S/SB/SBURKE/HTML-Tagset-3.02.tar.gz
S/SB/SBURKE/HTML-Tagset-3.03.tar.gz
S/SB/SBURKE/HTML-Tree-0.61.tar.gz
S/SB/SBURKE/HTML-Tree-0.65.tar.gz
S/SB/SBURKE/HTML-Tree-0.68.tar.gz
S/SB/SBURKE/HTML-Tree-3.05.tar.gz
S/SB/SBURKE/HTML-Tree-3.06.tar.gz
S/SB/SBURKE/HTML-Tree-3.07.tar.gz
S/SB/SBURKE/HTML-Tree-3.1.tar.gz
S/SB/SBURKE/HTML-Tree-3.11.tar.gz
S/SB/SBURKE/HTML-Tree-3.12.tar.gz
S/SB/SBURKE/HTML-Tree-3.13.tar.gz
S/SB/SBURKE/I18N-LangTags-0.23.tar.gz
S/SB/SBURKE/I18N-LangTags-0.24.tar.gz
S/SB/SBURKE/I18N-LangTags-0.26.tar.gz
S/SB/SBURKE/I18N-LangTags-0.27.tar.gz
S/SB/SBURKE/IO-Null-0.02.tar.gz
S/SB/SBURKE/Lingua-EN-Numbers-Ordinate-0.01.tar.gz
S/SB/SBURKE/Locale-Maketext-0.17.tar.gz
S/SB/SBURKE/Locale-Maketext-1.01.tar.gz
S/SB/SBURKE/Locale-Maketext-1.02.tar.gz
S/SB/SBURKE/Locale-Maketext-1.03.tar.gz
S/SB/SBURKE/MIDI-Perl-0.71.tar.gz
S/SB/SBURKE/MIDI-Perl-0.77.tar.gz
S/SB/SBURKE/MIDI-Perl-0.78.tar.gz
S/SB/SBURKE/MIDI-Perl-0.79.tar.gz
S/SB/SBURKE/Mac-FileSpec-Unixish-1.1.tar.gz
S/SB/SBURKE/Mac-FileSpec-Unixish-1.11.tar.gz
S/SB/SBURKE/Mac-RecentDocuments-0.01.tar.gz
S/SB/SBURKE/Pod-Escapes-1.02.tar.gz
S/SB/SBURKE/Pod-Escapes-1.03.tar.gz
S/SB/SBURKE/Pod-HTML2Pod-4.03.tar.gz
S/SB/SBURKE/RTF-Writer-1.06.tar.gz
S/SB/SBURKE/Sort-ArbBiLex-3.1.tar.gz
S/SB/SBURKE/Sort-ArbBiLex-3.11.tar.gz
S/SB/SBURKE/Sort-ArbBiLex-3.21.tar.gz
S/SB/SBURKE/Sort-ArbBiLex-3.31.tar.gz
S/SB/SBURKE/Sort-ArbBiLex-3.32.tar.gz
S/SB/SBURKE/Sort-ArbBiLex-3.4.tar.gz
S/SB/SBURKE/Test-1.21.tar.gz
S/SB/SBURKE/Test-1.22.tar.gz
S/SB/SBURKE/Tree-DAG_Node-0.75.tar.gz
S/SB/SBURKE/Tree-DAG_Node-1.03.tar.gz
S/SB/SBURKE/Tree-DAG_Node-1.04.tar.gz
S/SB/SBURKE/strict-ModuleName-0.03.tar.gz
S/SC/SCOTTZED/Bio-SAGE-Comparison-1.00.tar.gz
S/SC/SCOTTZED/Bio-SAGE-DataProcessing-1.10.tar.gz
S/SC/SCRESTO/Sys-MemInfo-0.4.tar.gz
S/SD/SDOWD/POP3Client-1_16.tar.gz
S/SK/SKUNZ/perlmenu.v3.3.tar.gz
S/SK/SKUNZ/perlmenu.v4.0.tar.gz
S/SL/SLEONOV/AIX-SysInfo-1.1.1.tar.gz
S/SL/SLEONOV/AIX-SysInfo-1.1.tar.gz
S/SL/SLEONOV/AIX-SysInfo-1.2.tar.gz
S/SP/SPIDB/Net-ext-0.74.tar.gz
S/SP/SPIDB/Net-ext-0.75.tar.gz
S/SP/SPIDB/Net-ext-0.79.tar.gz
S/SP/SPIDB/Net-ext-0.80.tar.gz
S/SP/SPIDB/Net-ext-0.81.tar.gz
S/SP/SPIDB/Net-ext-0.83.tar.gz
S/SP/SPIDB/Net-ext-0.84.tar.gz
S/SP/SPIDB/Net-ext-0.91.tar.gz
S/SP/SPIDB/Net-ext-0.933.tar.gz
S/SR/SREZIC/Netscape-Cache-0.2.tar.gz
S/ST/STBEY/Bit-ShiftReg-2.0.tar.gz
S/ST/STBEY/Bit-Vector-4.0.tar.gz
S/ST/STBEY/Bit-Vector-4.1.tar.gz
S/ST/STBEY/Bit-Vector-4.2.tar.gz
S/ST/STBEY/Bit-Vector-5.0b1.tar.gz
S/ST/STBEY/BitOps-ROL_ROR-2.0.tar.gz
S/ST/STBEY/Data-Locations-3.0.tar.gz
S/ST/STBEY/Data-Locations-4.3.tar.gz
S/ST/STBEY/DateCalc-1.2a.tar.gz
S/ST/STBEY/DateCalc-1.5.tar.gz
S/ST/STBEY/DateCalc-2.1.tar.gz
S/ST/STBEY/DateCalc-2.3.tar.gz
S/ST/STBEY/DateCalc-3.0.tar.gz
S/ST/STBEY/Graph-Kruskal-2.0.tar.gz
S/ST/STBEY/Locations-1.0.tar.gz
S/ST/STBEY/Math-MatrixBool-5.7.tar.gz
S/ST/STBEY/Math-MatrixReal-1.0.tar.gz
S/ST/STBEY/Math-MatrixReal-1.1.tar.gz
S/ST/STBEY/Math-MatrixReal-1.2.tar.gz
S/ST/STBEY/ROL_ROR-1.0.tar.gz
S/ST/STBEY/ROL_ROR-1.1.tar.gz
S/ST/STBEY/Set-IntegerFast-1.0.tar.gz
S/ST/STBEY/Set-IntegerFast-2.0.tar.gz
S/ST/STBEY/Set-IntegerFast-3.0.tar.gz
S/ST/STBEY/Set-IntegerFast-3.2.tar.gz
S/ST/STBEY/Set-IntegerFast-4.2.tar.gz
S/ST/STBEY/Set-IntegerRange-4.2.tar.gz
S/ST/STBEY/Tie-Handle-1.0.tar.gz
S/ST/STBEY/Tie-Handle-2.0.tar.gz
S/ST/STBEY/Tie-Handle-2.1.tar.gz
S/ST/STBEY/Tie-Handle-3.0.tar.gz
S/ST/STBEY/cartoons-1.0.tar.gz
S/ST/STLACY/HTML-Table-0.90.tar.gz
T/TA/TAYERS/Algorithm-LUHN-0.10.tar.gz
T/TA/TAYERS/Algorithm-LUHN-1.00.tar.gz
T/TA/TAYERS/Business-CINS-1.10.tar.gz
T/TA/TAYERS/Business-CINS-1.11.tar.gz
T/TA/TAYERS/Business-CINS-1.12.tar.gz
T/TA/TAYERS/Business-CINS-1.13.tar.gz
T/TA/TAYERS/Business-CUSIP-0.01.tar.gz
T/TA/TAYERS/Business-CUSIP-1.01.tar.gz
T/TA/TAYERS/Business-CUSIP-1.02.tar.gz
T/TA/TAYERS/Business-SEDOL-1.01.tar.gz
T/TA/TAYERS/Business-SEDOL-1.02.tar.gz
T/TA/TAYERS/List-Intersperse-1.00.tar.gz
T/TG/TGUMMELS/File-MkTemp-1.0.1.tar.gz
T/TG/TGUMMELS/File-MkTemp-1.0.2.tar.gz
T/TG/TGUMMELS/File-MkTemp-1.0.3.tar.gz
T/TG/TGUMMELS/File-MkTemp-1.0.4.tar.gz
T/TG/TGUMMELS/File-MkTemp-1.0.5.tar.gz
T/TG/TGUMMELS/File-MkTemp-1.0.6.tar.gz
T/TI/TIMB/DBI/DBI-0.64.tar.gz
T/TO/TOMC/modules/Date-GetDate-2.00.tar.gz
T/TO/TOMZO/Quota-0.1a.tar.gz
T/TR/TRIAS/Fame-2.0c.tar.gz
T/TR/TRIAS/Fame-2.0d.tar.gz
T/TR/TRIAS/Fame-2.tar.gz
T/TS/TSTANLEY/Config-Yacp-1.00.tar.gz
T/TS/TSTANLEY/Config-Yacp-1.1.tar.gz
T/TS/TSTANLEY/Games-QuizTaker-1.03.tar.gz
T/TS/TSTANLEY/Games-QuizTaker-1.08.tar.gz
T/TS/TSTANLEY/Games-QuizTaker-1.tar.gz
T/TS/TSTANLEY/Logger-Simple-1.01.tar.gz
T/TS/TSTANLEY/Logger-Simple-1.02.tar.gz
T/TS/TSTANLEY/Logger-Simple-1.03.tar.gz
T/TS/TSTANLEY/Logger-Simple-1.04.tar.gz
T/TS/TSTANLEY/Logger-Simple-1.05.tar.gz
T/TS/TSTANLEY/Logger-Simple-1.06.tar.gz
T/TS/TSTANLEY/Logger-Simple-1.07.tar.gz
T/TS/TSTANLEY/Logger-Simple-1.08.tar.gz
T/TS/TSTANLEY/Logger-Simple-1.081.tar.gz
U/UL/ULPFR/Logfile-0.112.tar.gz
U/UL/ULPFR/Logfile-0.113.tar.gz
U/UL/ULPFR/Math-Approx-0.1.tar.gz
U/UL/ULPFR/Math-Mathematica-1.0.4.tar.gz
U/UL/ULPFR/Math-Mathematica-1.0.5.tar.gz
U/UL/ULPFR/Math-Matrix-0.1.tar.gz
U/UL/ULPFR/Math-Matrix-0.2.tar.gz
U/UL/ULPFR/Net-Country-0.1.tar.gz
U/UL/ULPFR/Pconvert-1.04.tar.gz
U/UL/ULPFR/Text-German-0.03.tar.gz
U/UL/ULPFR/Wais-2.0.11.tar.gz
U/UL/ULPFR/Wais-2.1.0.tar.gz
U/UL/ULPFR/Wais-2.116.tar.gz
U/UL/ULPFR/perlindex-1.107.tar.gz
